"""cr.py: Capability CR generation goldens, validated through flokoa_types."""

from __future__ import annotations

import pytest
import yaml
from flokoa_types.capability import CapabilitySpec

from flokoa.capability_cli import cr
from flokoa.capability_cli.artifact import ArtifactManifest, ManifestRequires
from flokoa.capability_cli.errors import CapabilityCliError


def echo_manifest(**overrides: object) -> ArtifactManifest:
    fields: dict = {
        "name": "flokoa-cap-echo",
        "version": "0.1.0",
        "entrypoint": "flokoa_cap_echo:EchoCapability",
        "requires": ManifestRequires.model_validate({
            "python": "3.13",
            "pydantic-ai": ">=1.107,<2",
            "flokoa-runner": ">=0.2",
        }),
        "dependencies": [],
        "wheels": [{"file": "flokoa_cap_echo-0.1.0-py3-none-any.whl", "sha256": "a" * 64}],
        "config_schema": {
            "type": "object",
            "properties": {"prefix": {"type": "string", "default": "echo"}},
            "additionalProperties": False,
        },
    }
    fields.update(overrides)
    return ArtifactManifest(**fields)


GOLDEN_STRICT = """\
# Generated by `flokoa capability build`.
# spec.artifact carries a placeholder digest — run `flokoa capability push`
# to push the artifact, record the real digest, and rewrite this file.
# Admission refuses the CR until the placeholder is replaced.
apiVersion: agent.flokoa.ai/v1alpha1
kind: Capability
metadata:
  name: flokoa-cap-echo
spec:
  artifact: ghcr.io/example/capabilities/echo:0.1.0@sha256:DIGEST-PENDING
  version: 0.1.0
  entrypoint: flokoa_cap_echo:EchoCapability
  requires:
    python: '3.13'
    pydanticAI: '>=1.107,<2'
    flokoaRunner: '>=0.2'
  configSchema:
    type: object
    properties:
      prefix:
        type: string
        default: echo
    additionalProperties: false
"""


class TestRenderCapabilityCr:
    def test_strict_golden(self) -> None:
        rendered = cr.render_capability_cr(
            "flokoa-cap-echo", "ghcr.io/example/capabilities/echo:0.1.0", echo_manifest()
        )
        assert rendered == GOLDEN_STRICT

    def test_strict_spec_validates_through_generated_model(self) -> None:
        doc = cr.capability_cr_doc("flokoa-cap-echo", "ghcr.io/example/echo:0.1.0", echo_manifest())
        spec = {**doc["spec"], "artifact": "ghcr.io/example/echo:0.1.0@sha256:" + "0" * 64}
        validated = CapabilitySpec.model_validate(spec)
        assert validated.version == "0.1.0"
        assert validated.entrypoint == "flokoa_cap_echo:EchoCapability"
        assert validated.requires.pydantic_ai == ">=1.107,<2"
        assert validated.requires.flokoa_runner == ">=0.2"

    def test_dependencies_and_serialization_name_mirrored(self) -> None:
        manifest = echo_manifest(
            name="flokoa-cap-upper",
            entrypoint="flokoa_cap_upper:UpperCapability",
            serialization_name="Upper",
            dependencies=["inflection==0.5.1"],
        )
        doc = cr.capability_cr_doc("flokoa-cap-upper", "ghcr.io/example/upper:0.1.0", manifest)
        assert doc["spec"]["dependencies"] == ["inflection==0.5.1"]
        assert doc["spec"]["serializationName"] == "Upper"

    def test_permissive_sets_policy_and_omits_schema(self) -> None:
        manifest = echo_manifest(config_schema=None)
        doc = cr.capability_cr_doc("flokoa-cap-echo", "ghcr.io/example/echo:0.1.0", manifest, permissive=True)
        assert doc["spec"]["schemaPolicy"] == "permissive"
        assert "configSchema" not in doc["spec"]

    def test_strict_without_schema_refused(self) -> None:
        manifest = echo_manifest(config_schema=None)
        with pytest.raises(CapabilityCliError, match="strict Capability CR needs a configSchema"):
            cr.capability_cr_doc("flokoa-cap-echo", "ghcr.io/example/echo:0.1.0", manifest)

    def test_digest_placeholder_is_not_a_valid_digest(self) -> None:
        """Applying an unpushed CR must fail admission, not pull a bogus ref."""
        doc = cr.capability_cr_doc("flokoa-cap-echo", "ghcr.io/example/echo:0.1.0", echo_manifest())
        assert doc["spec"]["artifact"].endswith("@sha256:DIGEST-PENDING")
        with pytest.raises(Exception, match="artifact"):
            CapabilitySpec.model_validate(doc["spec"])

    def test_rendered_yaml_parses_back(self) -> None:
        rendered = cr.render_capability_cr("flokoa-cap-echo", "ghcr.io/example/echo:0.1.0", echo_manifest())
        doc = yaml.safe_load(rendered)
        assert doc["kind"] == "Capability"
        assert doc["apiVersion"] == "agent.flokoa.ai/v1alpha1"


class TestNameValidation:
    @pytest.mark.parametrize("name", ["flokoa-cap-echo", "echo", "a1", "ns.echo-2"])
    def test_dns_safe_names_accepted(self, name: str) -> None:
        assert cr.validate_cr_name(name) == name

    @pytest.mark.parametrize("name", ["Echo", "echo_cap", "-echo", "echo-", "", "a" * 254])
    def test_unsafe_names_refused(self, name: str) -> None:
        with pytest.raises(CapabilityCliError, match="not a DNS-safe"):
            cr.validate_cr_name(name)

    @pytest.mark.parametrize(
        ("dist", "normalized"),
        [
            ("flokoa_cap_echo", "flokoa-cap-echo"),
            ("Flokoa.Cap.Echo", "flokoa-cap-echo"),
            ("pydantic-ai-foo", "pydantic-ai-foo"),
        ],
    )
    def test_normalize_dist_name(self, dist: str, normalized: str) -> None:
        assert cr.normalize_dist_name(dist) == normalized
