"""Generated Pydantic v2 models from the flokoa CRD schemas.

Regenerated by `make generate-python-models` in `operator/` — do not edit the
generated modules by hand.
"""

from flokoa_types.agentcard import AgentCard
from flokoa_types.agenttool import AgentToolSpec
from flokoa_types.modelsettings import ModelSettings

__all__ = ["AgentCard", "AgentToolSpec", "ModelSettings"]
