# generated by datamodel-codegen:
#   filename:  agenttool_spec_schema.json
#   timestamp: 2026-06-11T18:41:31+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class SecretRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[
        str,
        Field(description="The key of the secret to select from.  Must be a valid secret key."),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
        ),
    ] = ""
    optional: Annotated[
        bool | None,
        Field(description="Specify whether the Secret or its key must be defined"),
    ] = None


class HeaderSecret(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[
        str,
        Field(
            description='Name is the HTTP header name (e.g. "Authorization").',
            min_length=1,
        ),
    ]
    secret_ref: Annotated[
        SecretRef,
        Field(
            alias="secretRef",
            description="SecretRef selects the Secret key holding the header value.",
        ),
    ]


class ServiceRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description="Name is the service name.", min_length=1)]
    namespace: Annotated[
        str | None,
        Field(description="Namespace is the service namespace. Defaults to the AgentTool's namespace."),
    ] = None
    port: Annotated[
        int | None,
        Field(
            description="Port is the service port number.\nMutually exclusive with PortName.",
            ge=1,
            le=65535,
        ),
    ] = None
    port_name: Annotated[
        str | None,
        Field(
            alias="portName",
            description="PortName is the service port name.\nMutually exclusive with Port.",
        ),
    ] = None


class Transport(Enum):
    streamable_http = "streamableHTTP"
    sse = "sse"


class Type(Enum):
    mcp = "mcp"
    openapi = "openapi"


class AgentToolSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    allowed_tools: Annotated[
        list[str] | None,
        Field(
            alias="allowedTools",
            description="AllowedTools filters the server's tools to this list.",
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Description is a human-readable description of the MCP server,\nsurfaced to the model where supported."
        ),
    ] = None
    header_secrets: Annotated[
        list[HeaderSecret] | None,
        Field(
            alias="headerSecrets",
            description="HeaderSecrets populate headers from Secrets. Values are delivered as\n${secret:…} placeholders resolved in the runner — never written into\nthe compiled spec.",
        ),
    ] = None
    headers: Annotated[
        dict[str, str] | None,
        Field(description="Headers are additional HTTP headers to send to the MCP server."),
    ] = None
    path: Annotated[
        str | None,
        Field(
            description='Path is the HTTP path of the MCP endpoint when using ServiceRef.\nDefaults to "/mcp" (streamableHTTP) or "/sse" (sse).'
        ),
    ] = None
    service_ref: Annotated[
        ServiceRef | None,
        Field(
            alias="serviceRef",
            description="ServiceRef references an in-cluster Service serving MCP.\nMutually exclusive with URL.",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(
            alias="timeoutSeconds",
            description="TimeoutSeconds is the request timeout in seconds for MCP calls.",
            ge=1,
            le=300,
        ),
    ] = None
    tool_prefix: Annotated[
        str | None,
        Field(
            alias="toolPrefix",
            description='ToolPrefix prefixes every tool name from this server (e.g. "petstore"\nturns "search" into "petstore_search"), avoiding collisions between\nservers.',
        ),
    ] = None
    transport: Annotated[
        Transport | None,
        Field(description="Transport selects the MCP transport protocol."),
    ] = "streamableHTTP"
    type: Annotated[Type | None, Field(description="Type specifies the kind of tool.")] = "mcp"
    url: Annotated[
        str | None,
        Field(description="URL is the full URL of the MCP server. Mutually exclusive with ServiceRef."),
    ] = None
