# generated by datamodel-codegen:
#   filename:  agenttool_spec_schema.json
#   timestamp: 2026-02-13T14:20:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ValueFrom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(description="The key to select.")]
    name: Annotated[
        str | None,
        Field(
            description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
        ),
    ] = ""
    optional: Annotated[
        bool | None,
        Field(description="Specify whether the ConfigMap or its key must be defined"),
    ] = None


class OpenApiSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    endpoint_path: Annotated[
        str | None,
        Field(
            alias="endpointPath",
            description='EndpointPath is a path on the target service/URL where the OpenAPI spec is served\n(e.g., "/openapi.json", "/docs/openapi.json", "/swagger.json").\nThe operator or runtime will fetch the spec from this path on the target.',
        ),
    ] = None
    value: Annotated[
        dict[str, Any] | None,
        Field(description="Value contains the OpenAPI specification inline."),
    ] = None
    value_from: Annotated[
        ValueFrom | None,
        Field(
            alias="valueFrom",
            description="ValueFrom references a ConfigMap containing the OpenAPI specification.",
        ),
    ] = None


class ServiceRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description="Name is the service name.", min_length=1)]
    namespace: Annotated[
        str | None,
        Field(description="Namespace is the service namespace. Defaults to the AgentTool's namespace."),
    ] = None
    port: Annotated[
        int | None,
        Field(
            description="Port is the service port number.\nMutually exclusive with PortName.",
            ge=1,
            le=65535,
        ),
    ] = None
    port_name: Annotated[
        str | None,
        Field(
            alias="portName",
            description="PortName is the service port name.\nMutually exclusive with Port.",
        ),
    ] = None


class OpenApi(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    headers: Annotated[
        dict[str, str] | None,
        Field(description="Headers are additional HTTP headers to include in API requests."),
    ] = None
    open_api_schema: Annotated[
        OpenApiSchema,
        Field(
            alias="openApiSchema",
            description="OpenApiSchema specifies the source of the OpenAPI specification.\nExactly one of Value, ValueFrom, or EndpointPath must be specified.",
        ),
    ]
    service_ref: Annotated[
        ServiceRef | None,
        Field(
            alias="serviceRef",
            description="ServiceRef references a Kubernetes service as the target API.\nMutually exclusive with URL.",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(
            alias="timeoutSeconds",
            description="TimeoutSeconds is the request timeout in seconds for API calls.",
            ge=1,
            le=300,
        ),
    ] = 30
    url: Annotated[
        str | None,
        Field(description="URL is the base URL of the external API.\nMutually exclusive with ServiceRef."),
    ] = None


class Type(Enum):
    openapi = "openapi"


class AgentToolSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Annotated[
        str,
        Field(
            description="Description is a human-readable description for the LLM to understand the tool's purpose.",
            min_length=1,
        ),
    ]
    open_api: Annotated[
        OpenApi | None,
        Field(
            alias="openApi",
            description='OpenApi contains OpenAPI tool configuration.\nRequired when Type is "openapi".',
        ),
    ] = None
    type: Annotated[Type, Field(description="Type specifies the kind of tool (e.g., openapi).")]
