# generated by datamodel-codegen:
#   filename:  agentworkflow_schema.json
#   timestamp: 2026-06-11T18:41:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WorkflowParam(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    description: Annotated[
        str | None, Field(description='Description of what this parameter is used for.')
    ] = None
    name: Annotated[str, Field(description='Name of the parameter.', min_length=1)]
    value: Annotated[
        str | None,
        Field(
            description='Value is the default parameter value. If empty, the parameter must be\nprovided at workflow submission time.'
        ),
    ] = None


class Authentication(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    credentials: Annotated[
        str | None,
        Field(
            description='Credentials is the authentication credential (e.g., a bearer token).'
        ),
    ] = None
    schemes: Annotated[
        list[str],
        Field(
            description='Schemes lists the authentication schemes supported (e.g., "Bearer").',
            min_length=1,
        ),
    ]


class PushNotificationConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    authentication: Annotated[
        Authentication | None,
        Field(
            description='Authentication configures authentication for push notification delivery.'
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description='ID is an optional identifier for this push notification configuration.'
        ),
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='Token is an opaque token the agent includes in push notifications for verification.'
        ),
    ] = None
    url: Annotated[
        str,
        Field(
            description='URL is the webhook endpoint to receive push notifications.',
            min_length=1,
        ),
    ]


class MessageSendConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    accepted_output_modes: Annotated[
        list[str] | None,
        Field(
            alias='acceptedOutputModes',
            description="AcceptedOutputModes restricts the agent's output format.",
        ),
    ] = None
    blocking: Annotated[
        bool | None,
        Field(
            description='Blocking indicates whether to wait synchronously for task completion.'
        ),
    ] = None
    history_length: Annotated[
        int | None,
        Field(
            alias='historyLength',
            description='HistoryLength limits the conversation history returned with the response.',
        ),
    ] = None
    push_notification_config: Annotated[
        PushNotificationConfig | None,
        Field(
            alias='pushNotificationConfig',
            description='PushNotificationConfig configures push notifications for async task updates.\nAligns with a2a.MessageSendConfig.PushNotificationConfig.',
        ),
    ] = None


class DataPart(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    data: Annotated[
        Any, Field(description='Data is arbitrary JSON data to send to the agent.')
    ]
    metadata: Annotated[
        dict[str, Any] | None, Field(description='Metadata for this part.')
    ] = None


class FileContent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    bytes: Annotated[
        str | None,
        Field(
            description='Bytes is the base64-encoded file content.\nExactly one of Bytes or URI must be set.'
        ),
    ] = None
    mime_type: Annotated[
        str | None, Field(alias='mimeType', description='MimeType of the file content.')
    ] = None
    name: Annotated[str | None, Field(description='Name of the file.')] = None
    uri: Annotated[
        str | None,
        Field(
            description='URI is a reference to the file location.\nExactly one of Bytes or URI must be set.'
        ),
    ] = None


class FilePart(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    file: Annotated[
        FileContent,
        Field(
            description='File content (either inline bytes or a URI reference).',
            title='FileContent',
        ),
    ]
    metadata: Annotated[
        dict[str, Any] | None, Field(description='Metadata for this part.')
    ] = None


class TextPart(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    metadata: Annotated[
        dict[str, Any] | None, Field(description='Metadata for this part.')
    ] = None
    text: Annotated[
        str,
        Field(
            description='Text content. Supports expressions like {{params.topic}} or {{tasks.prev.output}}.'
        ),
    ]


class MessagePart(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    data: Annotated[
        DataPart | None,
        Field(description='Data content part (structured JSON).', title='DataPart'),
    ] = None
    file: Annotated[
        FilePart | None, Field(description='File content part.', title='FilePart')
    ] = None
    text: Annotated[
        TextPart | None, Field(description='Text content part.', title='TextPart')
    ] = None


class MessageRole(Enum):
    user = 'user'
    agent = 'agent'


class AgentMessage(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    context_id: Annotated[
        str | None,
        Field(
            alias='contextId',
            description='ContextID for conversation threading across agent interactions.\nAligns with a2a.Message.ContextID.',
        ),
    ] = None
    extensions: Annotated[
        list[str] | None,
        Field(
            description='Extensions lists A2A extension URIs to activate for this message.\nAligns with a2a.Message.Extensions.'
        ),
    ] = None
    metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description='Metadata is arbitrary key-value metadata attached to the message.\nAligns with a2a.Message.Metadata.'
        ),
    ] = None
    parts: Annotated[
        list[MessagePart],
        Field(
            description='Parts is the content of the message. At least one part is required.',
            min_length=1,
        ),
    ]
    reference_task_ids: Annotated[
        list[str] | None,
        Field(
            alias='referenceTaskIds',
            description='ReferenceTaskIDs links this message to previous A2A task IDs.\nAligns with a2a.Message.ReferenceTasks.',
        ),
    ] = None
    role: Annotated[
        MessageRole | None,
        Field(description='Role of the message sender.', title='MessageRole'),
    ] = 'user'
    task_id: Annotated[
        str | None,
        Field(
            alias='taskId',
            description='TaskID continues an existing A2A task instead of creating a new one.\nAligns with a2a.Message.TaskID.',
        ),
    ] = None


class AgentCall(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    config: Annotated[
        MessageSendConfig | None,
        Field(
            description='Config configures how the message is sent to the agent.',
            title='MessageSendConfig',
        ),
    ] = None
    message: Annotated[
        AgentMessage | None,
        Field(
            description='Message is the full A2A message to send to the agent.\nMutually exclusive with Text. Use this for multi-part messages,\nfile attachments, or advanced message options.',
            title='AgentMessage',
        ),
    ] = None
    name: Annotated[
        str,
        Field(description='Name is the name of the Agent CR to call.', min_length=1),
    ]
    namespace: Annotated[
        str | None,
        Field(
            description='Namespace is the namespace of the Agent CR.\nDefaults to the workflow namespace.'
        ),
    ] = None
    text: Annotated[
        str | None,
        Field(
            description='Text is a shorthand for sending a simple text message.\nMutually exclusive with Message. When set, a single-part\nAgentMessage with this text is constructed automatically.\nSupports expressions like {{params.topic}} or {{tasks.prev.output}}.'
        ),
    ] = None


class AgentModelRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description='Name of the Model resource.', min_length=1)]
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace of the Model resource. Defaults to the referencing resource's namespace."
        ),
    ] = None


class InlineAgentSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    instructions: Annotated[
        str | None,
        Field(description='Instructions are behavioral instructions for this agent.'),
    ] = None
    model: Annotated[
        AgentModelRef | None,
        Field(
            description="Model references a Model CR for this agent's LLM.\nIf not specified, inherits the task-level model.",
            title='AgentModelRef',
        ),
    ] = None
    name: Annotated[str, Field(description='Name of the agent.', min_length=1)]


class ConfigMapKeySelector(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    key: Annotated[str, Field(description='The key to select.')]
    name: Annotated[
        str | None,
        Field(
            description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
        ),
    ] = ''
    optional: Annotated[
        bool | None,
        Field(description='Specify whether the ConfigMap or its key must be defined'),
    ] = None


class ObjectFieldSelector(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    api_version: Annotated[
        str | None,
        Field(
            alias='apiVersion',
            description='Version of the schema the FieldPath is written in terms of, defaults to "v1".',
        ),
    ] = None
    field_path: Annotated[
        str,
        Field(
            alias='fieldPath',
            description='Path of the field to select in the specified API version.',
        ),
    ]


class ResourceFieldSelector(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    container_name: Annotated[
        str | None,
        Field(
            alias='containerName',
            description='Container name: required for volumes, optional for env vars',
        ),
    ] = None
    divisor: Annotated[
        str | None,
        Field(
            description='Specifies the output format of the exposed resources, defaults to "1"',
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$',
        ),
    ] = None
    resource: Annotated[str, Field(description='Required: resource to select')]


class SecretKeySelector(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    key: Annotated[
        str,
        Field(
            description='The key of the secret to select from.  Must be a valid secret key.'
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
        ),
    ] = ''
    optional: Annotated[
        bool | None,
        Field(description='Specify whether the Secret or its key must be defined'),
    ] = None


class EnvVarSource(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    config_map_key_ref: Annotated[
        ConfigMapKeySelector | None,
        Field(
            alias='configMapKeyRef',
            description='Selects a key of a ConfigMap.',
            title='ConfigMapKeySelector',
        ),
    ] = None
    field_ref: Annotated[
        ObjectFieldSelector | None,
        Field(
            alias='fieldRef',
            description="Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,\nspec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
            title='ObjectFieldSelector',
        ),
    ] = None
    resource_field_ref: Annotated[
        ResourceFieldSelector | None,
        Field(
            alias='resourceFieldRef',
            description='Selects a resource of the container: only resources limits and requests\n(limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.',
            title='ResourceFieldSelector',
        ),
    ] = None
    secret_key_ref: Annotated[
        SecretKeySelector | None,
        Field(
            alias='secretKeyRef',
            description="Selects a key of a secret in the pod's namespace",
            title='SecretKeySelector',
        ),
    ] = None


class EnvVar(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str,
        Field(description='Name of the environment variable. Must be a C_IDENTIFIER.'),
    ]
    value: Annotated[
        str | None,
        Field(
            description='Variable references $(VAR_NAME) are expanded\nusing the previously defined environment variables in the container and\nany service environment variables. If a variable cannot be resolved,\nthe reference in the input string will be unchanged. Double $$ are reduced\nto a single $, which allows for escaping the $(VAR_NAME) syntax: i.e.\n"$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)".\nEscaped references will never be expanded, regardless of whether the variable\nexists or not.\nDefaults to "".'
        ),
    ] = None
    value_from: Annotated[
        EnvVarSource | None,
        Field(
            alias='valueFrom',
            description="Source for the environment variable's value. Cannot be used if value is not empty.",
            title='EnvVarSource',
        ),
    ] = None


class InstructionRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description='Name of the resource.', min_length=1)]
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace of the resource. Defaults to the referencing resource's namespace if not specified."
        ),
    ] = None


class InstructionEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    instruction_ref: Annotated[
        InstructionRef | None,
        Field(
            alias='instructionRef',
            description='InstructionRef references an existing Instruction resource.',
            title='InstructionRef',
        ),
    ] = None
    template: Annotated[
        str | None,
        Field(description='Template defines the instruction content directly.'),
    ] = None


class ResourceClaim(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str,
        Field(
            description='Name must match the name of one entry in pod.spec.resourceClaims of\nthe Pod where this field is used. It makes that resource available\ninside a container.'
        ),
    ]
    request: Annotated[
        str | None,
        Field(
            description='Request is the name chosen for a request in the referenced claim.\nIf empty, everything from the claim is made available, otherwise\nonly the result of this request.'
        ),
    ] = None


class ResourceRequirements(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    claims: Annotated[
        list[ResourceClaim] | None,
        Field(
            description='Claims lists the names of resources, defined in spec.resourceClaims,\nthat are used by this container.\n\nThis is an alpha field and requires enabling the\nDynamicResourceAllocation feature gate.\n\nThis field is immutable. It can only be set for containers.'
        ),
    ] = None
    limits: Annotated[
        dict[str, str] | None,
        Field(
            description='Limits describes the maximum amount of compute resources allowed.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
        ),
    ] = None
    requests: Annotated[
        dict[str, str] | None,
        Field(
            description='Requests describes the minimum amount of compute resources required.\nIf Requests is omitted for a container, it defaults to Limits if that is explicitly specified,\notherwise to an implementation-defined value. Requests cannot exceed Limits.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
        ),
    ] = None


class StructuredIOSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    description: str
    json_schema: Annotated[Any, Field(alias='jsonSchema')]
    name: str


class SecretRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    key: Annotated[
        str,
        Field(
            description='The key of the secret to select from.  Must be a valid secret key.'
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
        ),
    ] = ''
    optional: Annotated[
        bool | None,
        Field(description='Specify whether the Secret or its key must be defined'),
    ] = None


class HeaderSecret(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str,
        Field(
            description='Name is the HTTP header name (e.g. "Authorization").',
            min_length=1,
        ),
    ]
    secret_ref: Annotated[
        SecretRef,
        Field(
            alias='secretRef',
            description='SecretRef selects the Secret key holding the header value.',
        ),
    ]


class ServiceRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description='Name is the service name.', min_length=1)]
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace is the service namespace. Defaults to the AgentTool's namespace."
        ),
    ] = None
    port: Annotated[
        int | None,
        Field(
            description='Port is the service port number.\nMutually exclusive with PortName.',
            ge=1,
            le=65535,
        ),
    ] = None
    port_name: Annotated[
        str | None,
        Field(
            alias='portName',
            description='PortName is the service port name.\nMutually exclusive with Port.',
        ),
    ] = None


class Transport(Enum):
    streamable_http = 'streamableHTTP'
    sse = 'sse'


class Type(Enum):
    mcp = 'mcp'
    openapi = 'openapi'


class AgentToolSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    allowed_tools: Annotated[
        list[str] | None,
        Field(
            alias='allowedTools',
            description="AllowedTools filters the server's tools to this list.",
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description='Description is a human-readable description of the MCP server,\nsurfaced to the model where supported.'
        ),
    ] = None
    header_secrets: Annotated[
        list[HeaderSecret] | None,
        Field(
            alias='headerSecrets',
            description='HeaderSecrets populate headers from Secrets. Values are delivered as\n${secret:…} placeholders resolved in the runner — never written into\nthe compiled spec.',
        ),
    ] = None
    headers: Annotated[
        dict[str, str] | None,
        Field(
            description='Headers are additional HTTP headers to send to the MCP server.'
        ),
    ] = None
    path: Annotated[
        str | None,
        Field(
            description='Path is the HTTP path of the MCP endpoint when using ServiceRef.\nDefaults to "/mcp" (streamableHTTP) or "/sse" (sse).'
        ),
    ] = None
    service_ref: Annotated[
        ServiceRef | None,
        Field(
            alias='serviceRef',
            description='ServiceRef references an in-cluster Service serving MCP.\nMutually exclusive with URL.',
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(
            alias='timeoutSeconds',
            description='TimeoutSeconds is the request timeout in seconds for MCP calls.',
            ge=1,
            le=300,
        ),
    ] = None
    tool_prefix: Annotated[
        str | None,
        Field(
            alias='toolPrefix',
            description='ToolPrefix prefixes every tool name from this server (e.g. "petstore"\nturns "search" into "petstore_search"), avoiding collisions between\nservers.',
        ),
    ] = None
    transport: Annotated[
        Transport | None,
        Field(description='Transport selects the MCP transport protocol.'),
    ] = 'streamableHTTP'
    type: Annotated[
        Type | None, Field(description='Type specifies the kind of tool.')
    ] = 'mcp'
    url: Annotated[
        str | None,
        Field(
            description='URL is the full URL of the MCP server. Mutually exclusive with ServiceRef.'
        ),
    ] = None


class ToolRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str, Field(description='Name of the AgentTool resource.', min_length=1)
    ]
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace of the AgentTool. Defaults to the referencing resource's namespace."
        ),
    ] = None


class ToolEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str | None,
        Field(
            description='Name of the tool. Required for inline tools, used as identifier.',
            min_length=1,
        ),
    ] = None
    template: Annotated[
        AgentToolSpec | None,
        Field(
            description='Template defines the tool directly in the task spec.',
            title='AgentToolSpec',
        ),
    ] = None
    tool_ref: Annotated[
        ToolRef | None,
        Field(
            alias='toolRef',
            description='ToolRef references an existing AgentTool resource.',
            title='ToolRef',
        ),
    ] = None


class AgentTaskType(Enum):
    run = 'run'
    classify = 'classify'
    extract = 'extract'
    cast = 'cast'
    generate = 'generate'


class AgentTask(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    agent: Annotated[
        InlineAgentSpec | None,
        Field(
            description='Agent defines an inline agent for execution.',
            title='InlineAgentSpec',
        ),
    ] = None
    context: Annotated[
        dict[str, str] | None,
        Field(
            description='Context is key-value data passed to the task.\nValues support expressions like {{tasks.prev.output}}.'
        ),
    ] = None
    count: Annotated[
        int | None,
        Field(
            description='Count is the number of items to generate.\nOnly used when type=generate. Defaults to 1.',
            ge=1,
        ),
    ] = None
    env: Annotated[
        list[EnvVar] | None,
        Field(description='Env is additional environment variables for the container.'),
    ] = None
    image: Annotated[
        str | None, Field(description='Image overrides the container image.')
    ] = None
    input: Annotated[
        str | None,
        Field(
            description='Input is the data to process.\n- classify: data to classify (required)\n- extract: data to extract from (required)\n- cast: data to transform (required)\n- run/generate: not used\nSupports expressions like {{tasks.prev.output}}.'
        ),
    ] = None
    instruction: Annotated[
        InstructionEntry | None,
        Field(
            description='Instruction provides the prompt or guidance for the task.\n- run: the main prompt (required)\n- classify/extract/cast/generate: optional guidance instructions\nSupports inline text (template) or reference to an Instruction CR (instructionRef).',
            title='InstructionEntry',
        ),
    ] = None
    labels: Annotated[
        list[str] | None,
        Field(
            description='Labels for classify operations.\nRequired when type=classify.'
        ),
    ] = None
    model: Annotated[
        AgentModelRef | None,
        Field(
            description='Model references a Model CR for the LLM configuration.',
            title='AgentModelRef',
        ),
    ] = None
    multi_label: Annotated[
        bool | None,
        Field(
            alias='multiLabel',
            description='MultiLabel enables multi-label classification (returns list instead of single label).\nOnly used when type=classify.',
        ),
    ] = None
    resources: Annotated[
        ResourceRequirements | None,
        Field(
            description='Resources specifies compute resource requirements for the container.',
            title='ResourceRequirements',
        ),
    ] = None
    result_type: Annotated[
        StructuredIOSchema | None,
        Field(
            alias='resultType',
            description='ResultType constrains the output via JSON Schema.\n- run: optional (defaults to str)\n- extract: target type (defaults to str)\n- cast: target type (required)\n- generate: target type (required)\n- classify: not used (labels define the output)',
            title='StructuredIOSchema',
        ),
    ] = None
    tools: Annotated[
        list[ToolEntry] | None,
        Field(
            description='Tools available to the task. Can be inline definitions or references to AgentTool CRs.\nPrimarily used with type=run.'
        ),
    ] = None
    type: Annotated[
        AgentTaskType,
        Field(
            description='Type is the operation: run, classify, extract, cast, or generate.',
            title='AgentTaskType',
        ),
    ]


class ConfigMapKeyRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    key: Annotated[str, Field(description='The key to select.')]
    name: Annotated[
        str | None,
        Field(
            description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
        ),
    ] = ''
    optional: Annotated[
        bool | None,
        Field(description='Specify whether the ConfigMap or its key must be defined'),
    ] = None


class FieldRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    api_version: Annotated[
        str | None,
        Field(
            alias='apiVersion',
            description='Version of the schema the FieldPath is written in terms of, defaults to "v1".',
        ),
    ] = None
    field_path: Annotated[
        str,
        Field(
            alias='fieldPath',
            description='Path of the field to select in the specified API version.',
        ),
    ]


class Divisor(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='Specifies the output format of the exposed resources, defaults to "1"',
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$',
        ),
    ]


class Divisor1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Specifies the output format of the exposed resources, defaults to "1"',
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$',
        ),
    ]


class ResourceFieldRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    container_name: Annotated[
        str | None,
        Field(
            alias='containerName',
            description='Container name: required for volumes, optional for env vars',
        ),
    ] = None
    divisor: Annotated[
        Divisor | Divisor1 | None,
        Field(
            description='Specifies the output format of the exposed resources, defaults to "1"'
        ),
    ] = None
    resource: Annotated[str, Field(description='Required: resource to select')]


class SecretKeyRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    key: Annotated[
        str,
        Field(
            description='The key of the secret to select from.  Must be a valid secret key.'
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
        ),
    ] = ''
    optional: Annotated[
        bool | None,
        Field(description='Specify whether the Secret or its key must be defined'),
    ] = None


class ValueFrom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    config_map_key_ref: Annotated[
        ConfigMapKeyRef | None,
        Field(alias='configMapKeyRef', description='Selects a key of a ConfigMap.'),
    ] = None
    field_ref: Annotated[
        FieldRef | None,
        Field(
            alias='fieldRef',
            description="Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,\nspec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
        ),
    ] = None
    resource_field_ref: Annotated[
        ResourceFieldRef | None,
        Field(
            alias='resourceFieldRef',
            description='Selects a resource of the container: only resources limits and requests\n(limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.',
        ),
    ] = None
    secret_key_ref: Annotated[
        SecretKeyRef | None,
        Field(
            alias='secretKeyRef',
            description="Selects a key of a secret in the pod's namespace",
        ),
    ] = None


class EnvItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str,
        Field(description='Name of the environment variable. Must be a C_IDENTIFIER.'),
    ]
    value: Annotated[
        str | None,
        Field(
            description='Variable references $(VAR_NAME) are expanded\nusing the previously defined environment variables in the container and\nany service environment variables. If a variable cannot be resolved,\nthe reference in the input string will be unchanged. Double $$ are reduced\nto a single $, which allows for escaping the $(VAR_NAME) syntax: i.e.\n"$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)".\nEscaped references will never be expanded, regardless of whether the variable\nexists or not.\nDefaults to "".'
        ),
    ] = None
    value_from: Annotated[
        ValueFrom | None,
        Field(
            alias='valueFrom',
            description="Source for the environment variable's value. Cannot be used if value is not empty.",
        ),
    ] = None


class Claim(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[
        str,
        Field(
            description='Name must match the name of one entry in pod.spec.resourceClaims of\nthe Pod where this field is used. It makes that resource available\ninside a container.'
        ),
    ]
    request: Annotated[
        str | None,
        Field(
            description='Request is the name chosen for a request in the referenced claim.\nIf empty, everything from the claim is made available, otherwise\nonly the result of this request.'
        ),
    ] = None


class Limits(RootModel[int]):
    root: Annotated[
        int,
        Field(
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'
        ),
    ]


class Limits1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'
        ),
    ]


class Requests(RootModel[int]):
    root: Annotated[
        int,
        Field(
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'
        ),
    ]


class Requests1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$'
        ),
    ]


class Resources(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    claims: Annotated[
        list[Claim] | None,
        Field(
            description='Claims lists the names of resources, defined in spec.resourceClaims,\nthat are used by this container.\n\nThis is an alpha field and requires enabling the\nDynamicResourceAllocation feature gate.\n\nThis field is immutable. It can only be set for containers.'
        ),
    ] = None
    limits: Annotated[
        dict[str, Limits | Limits1] | None,
        Field(
            description='Limits describes the maximum amount of compute resources allowed.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
        ),
    ] = None
    requests: Annotated[
        dict[str, Requests | Requests1] | None,
        Field(
            description='Requests describes the minimum amount of compute resources required.\nIf Requests is omitted for a container, it defaults to Limits if that is explicitly specified,\notherwise to an implementation-defined value. Requests cannot exceed Limits.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
        ),
    ] = None


class VolumeMount(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    mount_path: Annotated[
        str,
        Field(
            alias='mountPath',
            description="Path within the container at which the volume should be mounted.  Must\nnot contain ':'.",
        ),
    ]
    mount_propagation: Annotated[
        str | None,
        Field(
            alias='mountPropagation',
            description='mountPropagation determines how mounts are propagated from the host\nto container and the other way around.\nWhen not set, MountPropagationNone is used.\nThis field is beta in 1.10.\nWhen RecursiveReadOnly is set to IfPossible or to Enabled, MountPropagation must be None or unspecified\n(which defaults to None).',
        ),
    ] = None
    name: Annotated[str, Field(description='This must match the Name of a Volume.')]
    read_only: Annotated[
        bool | None,
        Field(
            alias='readOnly',
            description='Mounted read-only if true, read-write otherwise (false or unspecified).\nDefaults to false.',
        ),
    ] = None
    recursive_read_only: Annotated[
        str | None,
        Field(
            alias='recursiveReadOnly',
            description='RecursiveReadOnly specifies whether read-only mounts should be handled\nrecursively.\n\nIf ReadOnly is false, this field has no meaning and must be unspecified.\n\nIf ReadOnly is true, and this field is set to Disabled, the mount is not made\nrecursively read-only.  If this field is set to IfPossible, the mount is made\nrecursively read-only, if it is supported by the container runtime.  If this\nfield is set to Enabled, the mount is made recursively read-only if it is\nsupported by the container runtime, otherwise the pod will not be started and\nan error will be generated to indicate the reason.\n\nIf this field is set to IfPossible or Enabled, MountPropagation must be set to\nNone (or be unspecified, which defaults to None).\n\nIf this field is not specified, it is treated as an equivalent of Disabled.',
        ),
    ] = None
    sub_path: Annotated[
        str | None,
        Field(
            alias='subPath',
            description='Path within the volume from which the container\'s volume should be mounted.\nDefaults to "" (volume\'s root).',
        ),
    ] = None
    sub_path_expr: Annotated[
        str | None,
        Field(
            alias='subPathExpr',
            description='Expanded path within the volume from which the container\'s volume should be mounted.\nBehaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container\'s environment.\nDefaults to "" (volume\'s root).\nSubPathExpr and SubPath are mutually exclusive.',
        ),
    ] = None


class Container(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    args: Annotated[
        list[str] | None, Field(description='Args are arguments to the command.')
    ] = None
    command: Annotated[
        list[str] | None, Field(description='Command is the entrypoint command.')
    ] = None
    env: Annotated[
        list[EnvItem] | None,
        Field(
            description='Env is additional environment variables for the container.\nValues support DSL expressions like {{params.x}} or {{tasks.prev.output}}.'
        ),
    ] = None
    image: Annotated[
        str, Field(description='Image is the container image to run.', min_length=1)
    ]
    resources: Annotated[
        Resources | None,
        Field(
            description='Resources specifies compute resource requirements for the container.'
        ),
    ] = None
    volume_mounts: Annotated[
        list[VolumeMount] | None,
        Field(
            alias='volumeMounts',
            description='VolumeMounts are volume mounts for the container.',
        ),
    ] = None
    working_dir: Annotated[
        str | None,
        Field(
            alias='workingDir',
            description='WorkingDir is the working directory inside the container.',
        ),
    ] = None


class ValueFrom1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    config_map_key_ref: Annotated[
        ConfigMapKeyRef | None,
        Field(
            alias='configMapKeyRef',
            description='ConfigMapKeyRef references a key in a Kubernetes ConfigMap.',
        ),
    ] = None
    secret_key_ref: Annotated[
        SecretKeyRef | None,
        Field(
            alias='secretKeyRef',
            description='SecretKeyRef references a key in a Kubernetes Secret.',
        ),
    ] = None


class Header(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description='Name is the header name.', min_length=1)]
    value: Annotated[
        str | None,
        Field(
            description='Value is the header value. Supports DSL expressions.\nMutually exclusive with ValueFrom.'
        ),
    ] = None
    value_from: Annotated[
        ValueFrom1 | None,
        Field(
            alias='valueFrom',
            description='ValueFrom references a secret or configmap key for the header value.\nMutually exclusive with Value.',
        ),
    ] = None


class Method(Enum):
    get = 'GET'
    post = 'POST'
    put = 'PUT'
    delete = 'DELETE'
    patch = 'PATCH'
    head = 'HEAD'
    options = 'OPTIONS'


class Http(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    body: Annotated[
        str | None,
        Field(description='Body is the HTTP request body. Supports DSL expressions.'),
    ] = None
    headers: Annotated[
        list[Header] | None,
        Field(description='Headers are HTTP headers to include in the request.'),
    ] = None
    method: Annotated[
        Method | None, Field(description='Method is the HTTP method to use.')
    ] = 'GET'
    success_condition: Annotated[
        str | None,
        Field(
            alias='successCondition',
            description='SuccessCondition is an Argo-native expression evaluated against the HTTP response\nto determine if the request was successful (e.g., "response.statusCode == 200").',
        ),
    ] = None
    url: Annotated[
        str,
        Field(
            description='URL is the HTTP request URL. Supports DSL expressions.',
            min_length=1,
        ),
    ]


class SwitchCase(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    condition: Annotated[
        str | None,
        Field(
            description='Condition is an expression evaluated against available task outputs.'
        ),
    ] = None
    default: Annotated[
        str | None,
        Field(
            description='Default is the fallback task name if no other condition matches.'
        ),
    ] = None
    then: Annotated[
        str | None,
        Field(description='Then is the task name to run if the condition is true.'),
    ] = None


class WorkflowBackoff(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    duration: Annotated[
        str,
        Field(
            description='Duration is the initial backoff duration (e.g., "30s", "5m").'
        ),
    ]
    factor: Annotated[
        int | None,
        Field(
            description='Factor is the multiplier applied to the duration after each retry.'
        ),
    ] = None


class WorkflowRetryStrategy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    backoff: Annotated[
        WorkflowBackoff | None,
        Field(
            description='Backoff configures the backoff strategy between retries.',
            title='WorkflowBackoff',
        ),
    ] = None
    limit: Annotated[
        int, Field(description='Limit is the maximum number of retry attempts.', ge=0)
    ]


class WorkflowTask(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    agent: Annotated[
        AgentCall | None,
        Field(
            description='Agent calls a deployed Agent CR via the A2A protocol.',
            title='AgentCall',
        ),
    ] = None
    agent_task: Annotated[
        AgentTask | None,
        Field(
            alias='agentTask',
            description='AgentTask is no longer supported. The AgentWorkflow API is frozen and\nthe agentTask runtime was removed in the v2.1 pivot; the field is kept\nonly for API compatibility with existing objects. The admission webhook\nrejects new usage and the compiler refuses to compile it.\n\nDeprecated: use an agent task calling a deployed Agent instead.',
            title='AgentTask',
        ),
    ] = None
    condition: Annotated[
        str | None,
        Field(
            description='Condition is an expression that must evaluate to true for this task to run.\nIf false, the task is skipped.'
        ),
    ] = None
    container: Annotated[
        Container | None,
        Field(
            description='Container runs an arbitrary container workload.\nThe container should write its result to /tmp/result and optional\nstructured output to /tmp/artifact.'
        ),
    ] = None
    depends_on: Annotated[
        list[str] | None,
        Field(
            alias='dependsOn',
            description='DependsOn lists task names that must complete before this task starts.\nDefines DAG edges.',
        ),
    ] = None
    http: Annotated[
        Http | None,
        Field(
            description='HTTP makes an HTTP request to an external service.\nThe response body is captured as the task output.'
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description='Name is the unique identifier for this task within the workflow.',
            min_length=1,
            pattern='^[a-zA-Z0-9][-a-zA-Z0-9]*$',
        ),
    ]
    retry_strategy: Annotated[
        WorkflowRetryStrategy | None, Field(alias='retryStrategy')
    ] = None
    switch: Annotated[
        list[SwitchCase] | None,
        Field(
            description='Switch routes to different tasks based on the output of a previous task.'
        ),
    ] = None
    timeout: Annotated[
        str | None, Field(description='Timeout is the maximum duration for this task.')
    ] = None


class AgentWorkflowSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    automount_service_account_token: Annotated[
        bool | None,
        Field(
            alias='automountServiceAccountToken',
            description='AutomountServiceAccountToken controls whether the service account token\nis automatically mounted into workflow pods. Defaults to true.\nArgo executor plugins require this to be true.',
        ),
    ] = True
    description: Annotated[
        str | None,
        Field(
            description='Description is a human-readable description of the workflow.'
        ),
    ] = None
    params: Annotated[
        list[WorkflowParam] | None,
        Field(
            description='Params are workflow-level parameters that can be referenced in expressions.'
        ),
    ] = None
    retry_strategy: Annotated[
        WorkflowRetryStrategy | None, Field(alias='retryStrategy')
    ] = None
    service_account_name: Annotated[
        str | None,
        Field(
            alias='serviceAccountName',
            description='ServiceAccountName is the Kubernetes ServiceAccount used for workflow pods.\nDefaults to "flokoa-workflow" if not specified.',
        ),
    ] = 'flokoa-workflow'
    tasks: Annotated[
        list[WorkflowTask],
        Field(description='Tasks defines the workflow tasks to execute.', min_length=1),
    ]
    timeout: Annotated[
        str | None,
        Field(description='Timeout is the maximum duration for the entire workflow.'),
    ] = None
