# generated by datamodel-codegen:
#   filename:  agentcard_schema.json
#   timestamp: 2026-02-21T10:14:51+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Extension(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    params: dict[str, Any] | None = None
    required: bool | None = None
    uri: str | None = None


class Capabilities(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    extensions: list[Extension] | None = None
    push_notifications: Annotated[bool | None, Field(alias='pushNotifications')] = None
    state_transition_history: Annotated[
        bool | None, Field(alias='stateTransitionHistory')
    ] = None
    streaming: bool | None = None


class Skill(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Annotated[
        str, Field(description='Detailed description of what the skill does')
    ]
    examples: Annotated[
        list[str] | None,
        Field(description='Sample prompts or use cases demonstrating the skill'),
    ] = None
    id: Annotated[str, Field(description='Unique identifier for the skill')]
    input_modes: Annotated[
        list[str] | None,
        Field(
            alias='inputModes',
            description="Supported input MIME types for this skill, overriding the agent's defaults",
        ),
    ] = None
    name: Annotated[str, Field(description='Human-readable name for the skill')]
    output_modes: Annotated[
        list[str] | None,
        Field(
            alias='outputModes',
            description="Supported output MIME types for this skill, overriding the agent's defaults",
        ),
    ] = None
    security: Annotated[
        list[dict[str, list[str]]] | None,
        Field(
            description='Security schemes necessary for the agent to leverage this skill\nEach map entry represents security schemes that must be used together (AND)\nMultiple entries represent alternatives (OR)'
        ),
    ] = None
    tags: Annotated[
        list[str], Field(description='Keywords for categorization and discovery')
    ]


class AgentCard(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    capabilities: Annotated[
        Capabilities,
        Field(
            default_factory=lambda: Capabilities.model_validate({'streaming': False})
        ),
    ]
    default_input_modes: Annotated[list[str], Field(alias='defaultInputModes')]
    default_output_modes: Annotated[list[str], Field(alias='defaultOutputModes')]
    description: str
    name: str
    skills: list[Skill]
    version: str
