# generated by datamodel-codegen:
#   filename:  capability_schema.json
#   timestamp: 2026-06-12T15:26:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Dependency(RootModel[str]):
    root: Annotated[
        str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._-]*==[A-Za-z0-9._+!-]+$')
    ]


class CapabilityProvenance(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    signature_ref: Annotated[
        str | None,
        Field(
            alias='signatureRef',
            description="SignatureRef optionally records where the artifact's cosign signature\nlives when it is not the default sidecar tag in the artifact repository.",
        ),
    ] = None


class CapabilityRequires(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flokoa_runner: Annotated[
        str | None,
        Field(
            alias='flokoaRunner',
            description='FlokoaRunner is a PEP 440 specifier set for the runner release,\ne.g. ">=0.2".',
        ),
    ] = None
    pydantic_ai: Annotated[
        str | None,
        Field(
            alias='pydanticAI',
            description='PydanticAI is a PEP 440 specifier set for the runner\'s pydantic-ai\ncore pin, e.g. ">=1.107,<2".',
        ),
    ] = None
    python: Annotated[
        str | None,
        Field(
            description='Python is the required Python minor (exact match), e.g. "3.13".',
            pattern='^\\d+\\.\\d+$',
        ),
    ] = None


class SchemaPolicy(Enum):
    strict = 'strict'
    permissive = 'permissive'


class CapabilitySpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    artifact: Annotated[
        str,
        Field(
            description='Artifact is the OCI reference of the wheelhouse artifact image\n(runtime contract §4). MUST be digest-pinned.',
            pattern='@sha256:[a-f0-9]{64}$',
        ),
    ]
    config_schema: Annotated[
        Any | None,
        Field(
            alias='configSchema',
            description='ConfigSchema is the JSON Schema for per-agent config, validated\noffline at admission. Required unless schemaPolicy is permissive.',
        ),
    ] = None
    dependencies: Annotated[
        list[Dependency] | None,
        Field(
            description="Dependencies mirrors the artifact's pinned dependency closure\n(name==version) for admission-time conflict detection without registry\naccess."
        ),
    ] = None
    entrypoint: Annotated[
        str,
        Field(
            description='Entrypoint is the Python `module:attr` resolving to the capability\nclass (a pydantic-ai AbstractCapability subclass).',
            pattern='^[\\w.]+:[\\w.]+$',
        ),
    ]
    provenance: Annotated[
        CapabilityProvenance | None,
        Field(
            description='Provenance carries signature/attestation metadata (cosign verification\nconfig lands with roadmap 09).',
            title='CapabilityProvenance',
        ),
    ] = None
    requires: Annotated[
        CapabilityRequires,
        Field(
            description='Requires is the compatibility tuple, mirrored from the artifact\nmanifest.',
            title='CapabilityRequires',
        ),
    ]
    schema_policy: Annotated[
        SchemaPolicy | None,
        Field(
            alias='schemaPolicy',
            description='SchemaPolicy: strict (default) requires ConfigSchema; permissive is\nthe loud opt-out.',
            title='SchemaPolicy',
        ),
    ] = 'strict'
    serialization_name: Annotated[
        str | None,
        Field(
            alias='serializationName',
            description="SerializationName is the capability's spec-entry name when the class\noverrides pydantic-ai's default (the class name). Compiled specs\nreference the capability by this name; defaults to the attr part of\nentrypoint.",
        ),
    ] = None
    version: Annotated[
        str,
        Field(
            description="Version is the capability's own semantic version (matches the artifact\nmanifest).",
            min_length=1,
        ),
    ]
