# generated by datamodel-codegen:
#   filename:  capability_schema.json
#   timestamp: 2026-06-15T10:58:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Dependency(RootModel[str]):
    root: Annotated[
        str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._-]*==[A-Za-z0-9._+!-]+$')
    ]


class Git(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    commit: Annotated[
        str,
        Field(
            description='Commit is the resolved git commit the artifact was built from.',
            pattern='^[a-f0-9]{7,40}$',
        ),
    ]
    ref: Annotated[
        str | None,
        Field(
            description='Ref is the requested branch, tag, or commit (informational).'
        ),
    ] = None
    subdirectory: Annotated[
        str | None,
        Field(
            description='Subdirectory is the path within the repo to the Python project, if any.'
        ),
    ] = None
    url: Annotated[
        str,
        Field(description='URL is the clean repository URL (no embedded credentials).'),
    ]


class Pypi(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    requirement: Annotated[
        str,
        Field(
            description='Requirement is the resolved PyPI requirement, e.g. "some-pkg==1.2.0".'
        ),
    ]


class CapabilityProvenance(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    git: Annotated[
        Git | None,
        Field(
            description='Git records the git origin a `source: git` capability was built from\n(repo URL + resolved commit). The resolved commit is the durable record:\neven if the branch/tag moves, this captures the exact code built.'
        ),
    ] = None
    pypi: Annotated[
        Pypi | None,
        Field(
            description='Pypi records the PyPI requirement a `source: pypi` capability was built\nfrom.'
        ),
    ] = None
    signature_ref: Annotated[
        str | None,
        Field(
            alias='signatureRef',
            description="SignatureRef optionally records where the artifact's cosign signature\nlives when it is not the default sidecar tag in the artifact repository.",
        ),
    ] = None


class CapabilityRequires(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flokoa_runner: Annotated[
        str | None,
        Field(
            alias='flokoaRunner',
            description='FlokoaRunner is a PEP 440 specifier set for the runner release,\ne.g. ">=0.2".',
        ),
    ] = None
    pydantic_ai: Annotated[
        str | None,
        Field(
            alias='pydanticAI',
            description='PydanticAI is a PEP 440 specifier set for the runner\'s pydantic-ai\ncore pin, e.g. ">=1.107,<2".',
        ),
    ] = None
    python: Annotated[
        str | None,
        Field(
            description='Python is the required Python minor (exact match), e.g. "3.13".',
            pattern='^\\d+\\.\\d+$',
        ),
    ] = None


class SchemaPolicy(Enum):
    strict = 'strict'
    permissive = 'permissive'


class Source(Enum):
    builtin = 'builtin'
    image = 'image'
    git = 'git'
    pypi = 'pypi'


class CapabilitySpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    artifact: Annotated[
        str | None,
        Field(
            description='Artifact is the OCI reference of the wheelhouse artifact image\n(runtime contract §4). MUST be digest-pinned when present. Required for\nsource image/git/pypi; forbidden for source builtin (no artifact is\ndelivered — the code is in the runner image).',
            pattern='^$|@sha256:[a-f0-9]{64}$',
        ),
    ] = None
    config_schema: Annotated[
        Any | None,
        Field(
            alias='configSchema',
            description='ConfigSchema is the JSON Schema for per-agent config, validated\noffline at admission. Required unless schemaPolicy is permissive.',
        ),
    ] = None
    dependencies: Annotated[
        list[Dependency] | None,
        Field(
            description="Dependencies mirrors the artifact's pinned dependency closure\n(name==version) for admission-time conflict detection without registry\naccess."
        ),
    ] = None
    entrypoint: Annotated[
        str,
        Field(
            description="Entrypoint is the Python `module:attr` resolving to the capability\nclass (a pydantic-ai AbstractCapability subclass). The attr must be the\nclass itself, bound in the module under its own __name__ — no factories\nor re-export aliases — so the compiled spec entry name (the class name,\npydantic-ai's default) resolves at hydration. If the class overrides\nget_serialization_name(), set serializationName to match.",
            pattern='^[\\w.]+:[A-Za-z_]\\w*$',
        ),
    ]
    provenance: Annotated[
        CapabilityProvenance | None,
        Field(
            description='Provenance carries signature/attestation metadata (cosign verification\nconfig lands with roadmap 09).',
            title='CapabilityProvenance',
        ),
    ] = None
    requires: Annotated[
        CapabilityRequires,
        Field(
            description='Requires is the compatibility tuple, mirrored from the artifact\nmanifest.',
            title='CapabilityRequires',
        ),
    ]
    schema_policy: Annotated[
        SchemaPolicy | None,
        Field(
            alias='schemaPolicy',
            description='SchemaPolicy: strict (default) requires ConfigSchema; permissive is\nthe loud opt-out.',
            title='SchemaPolicy',
        ),
    ] = 'strict'
    serialization_name: Annotated[
        str | None,
        Field(
            alias='serializationName',
            description="SerializationName is the capability's spec-entry name when the class\noverrides pydantic-ai's default (the class name). Compiled specs\nreference the capability by this name; defaults to the attr part of\nentrypoint. It may carry a first-party dotted namespace (e.g.\nflokoa.OpenAPI for built-ins) but no '/' or ':' path punctuation; the\noperator-injected flokoa.platform/ prefix is reserved. The webhook\nenforces the bare-class-name rule for user (image/git/pypi) capabilities\nand the dot-tolerant rule for source: builtin.",
            pattern='^[A-Za-z_][\\w.]*$',
        ),
    ] = None
    source: Annotated[
        Source | None,
        Field(
            description="Source records where the capability's code came from (builtin|image|\ngit|pypi). Defaults to image (the author-built-their-own case). The\nartifact field is REQUIRED for image/git/pypi and FORBIDDEN for builtin\n(built-in capabilities are baked into the runner image, never delivered)."
        ),
    ] = 'image'
    version: Annotated[
        str,
        Field(
            description="Version is the capability's own semantic version (matches the artifact\nmanifest).",
            min_length=1,
        ),
    ]
