# generated by datamodel-codegen:
#   filename:  taskconfig_schema.json
#   timestamp: 2026-02-16T22:14:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    run = "run"
    classify = "classify"
    extract = "extract"
    cast = "cast"
    generate = "generate"


class TaskResultType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description="Name of the result type.")]
    description: Annotated[str, Field(description="Description of the result type.")]
    json_schema: Annotated[
        Any,
        Field(
            alias="jsonSchema", description="JSON Schema defining the result structure."
        ),
    ]


class TaskAgentConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    name: Annotated[str, Field(description="Agent name.")]
    instructions: Annotated[str | None, Field(description="Agent instructions.")] = None


class TaskConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        populate_by_alias=True,
    )
    type: Annotated[Type, Field(description="The Marvin operation to perform.")]
    instructions: Annotated[
        str | None, Field(description="Prompt or guidance for the task.")
    ] = None
    input: Annotated[
        str | None, Field(description="Data to process (classify, extract, cast).")
    ] = None
    result_type: Annotated[
        TaskResultType | None,
        Field(
            alias="resultType",
            description="Output type constraint via JSON Schema.",
            title="TaskResultType",
        ),
    ] = None
    labels: Annotated[
        list[str] | None, Field(description="Labels for classify operations.")
    ] = None
    multi_label: Annotated[
        bool | None,
        Field(alias="multiLabel", description="Enable multi-label classification."),
    ] = None
    count: Annotated[
        int | None, Field(description="Number of items to generate.", ge=1)
    ] = None
    context: Annotated[
        dict[str, str] | None,
        Field(description="Key-value context data passed to Marvin."),
    ] = None
    agent: Annotated[
        TaskAgentConfig | None,
        Field(
            description="Inline Marvin agent configuration.", title="TaskAgentConfig"
        ),
    ] = None
