# GPT-4 Omni Model
apiVersion: agent.flokoa.ai/v1alpha1
kind: Model
metadata:
  name: gpt-4o
  labels:
    provider: openai
    model: gpt-4o
spec:
  model: "gpt-4o"
  
  providerRef:
    name: openai-provider
  
  settings:
    temperature: "0.7"
    maxTokens: 8192
    topP: "0.9"
