apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system

namePrefix: flokoa-

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: server
    newName: ghcr.io/danielnyari/flokoa-server
    newTag: latest
