repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^(docs/|operator/charts/.*|operator/test/e2e/testdata/.*\.yaml)$
      - id: check-json
        exclude: ^(.devcontainer/devcontainer.json|schemas/.*\.schema\.json)
      - id: pretty-format-json
        exclude: ^(.devcontainer/devcontainer.json|schemas/.*\.schema\.json)
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
        exclude: ^schemas/.*\.schema\.json$
      - id: trailing-whitespace
        exclude: ^schemas/.*\.schema\.json$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.8"
    hooks:
      - id: ruff-check
        args: [ --fix, --config=sdk/python/pyproject.toml ]
        exclude: (^sdk/python/flokoa/tests/|^sdk/python/flokoa/src/flokoa/tools|^sdk/python/flokoa/src/flokoa/auth|^sdk/python/flokoa/src/flokoa/utils)
      - id: ruff-format
        args: [ --config=sdk/python/pyproject.toml ]
        exclude: (^sdk/python/flokoa/tests/|^sdk/python/flokoa/src/flokoa/tools|^sdk/python/flokoa/src/flokoa/auth|^sdk/python/flokoa/src/flokoa/utils)
