# generated by datamodel-codegen:
#   filename:  agenttool_spec_schema.json
#   timestamp: 2026-01-24T22:39:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Method(Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"


class ServiceRef(BaseModel):
    name: str = Field(..., description="Service name")
    namespace: str | None = Field(None, description="Namespace (defaults to AgentTool's namespace)")
    port: int | None = Field(None, description="Port number")
    portName: str | None = Field(None, description="Port name (alternative to port number)")


class HttpApi(BaseModel):
    headers: dict[str, str] | None = Field(None, description="HTTP headers to include")
    method: Method = Field(..., description="HTTP method")
    path: str | None = Field(
        None,
        description="Path on the service (used with serviceRef, or appended to URL)",
    )
    serviceRef: ServiceRef | None = Field(None, description="Reference to a Kubernetes service (alternative to URL)")
    timeoutSeconds: int | None = Field(30, description="Timeout in seconds")
    url: str | None = Field(None, description="External API URL")


class ConfigMapRef(BaseModel):
    key: str = Field(..., description="Key in the ConfigMap")
    name: str = Field(..., description="ConfigMap name")


class OpenApiSchemaRef(BaseModel):
    configMapRef: ConfigMapRef | None = Field(None, description="Reference to a ConfigMap containing the OpenAPI spec")
    url: str | None = Field(None, description="URL to fetch the OpenAPI spec from")


class Type(Enum):
    http_api = "http-api"


class AgentToolSpec(BaseModel):
    description: str = Field(..., description="Human-readable description for the LLM")
    httpApi: HttpApi | None = Field(None, description="HTTP API specific configuration")
    inputSchema: dict[str, Any] | None = Field(
        None,
        description="Input schema - JSON Schema defining what the agent provides\nFor GET: becomes query params, for POST/PUT/PATCH: becomes JSON body",
    )
    openApiSchemaRef: OpenApiSchemaRef | None = Field(
        None,
        description="Reference to an OpenAPI spec (alternative to inputSchema/outputSchema)",
    )
    outputSchema: dict[str, Any] | None = Field(
        None, description="Output schema - JSON Schema defining what the tool returns"
    )
    type: Type = Field(..., description="Type of tool")
