# generated by datamodel-codegen:
#   filename:  agentcard_schema.json
#   timestamp: 2026-01-27T21:39:37+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Extension(BaseModel):
    description: str | None = None
    params: dict[str, Any] | None = None
    required: bool | None = None
    uri: str | None = None


class Capabilities(BaseModel):
    extensions: list[Extension] | None = None
    pushNotifications: bool | None = None
    stateTransitionHistroy: bool | None = None
    streaming: bool | None = None


class Skill(BaseModel):
    description: str = Field(..., description="Detailed description of what the skill does")
    examples: list[str] | None = Field(None, description="Sample prompts or use cases demonstrating the skill")
    id: str = Field(..., description="Unique identifier for the skill")
    inputModes: list[str] | None = Field(
        None,
        description="Supported input MIME types for this skill, overriding the agent's defaults",
    )
    name: str = Field(..., description="Human-readable name for the skill")
    outputModes: list[str] | None = Field(
        None,
        description="Supported output MIME types for this skill, overriding the agent's defaults",
    )
    security: list[dict[str, list[str]]] | None = Field(
        None,
        description="Security schemes necessary for the agent to leverage this skill\nEach map entry represents security schemes that must be used together (AND)\nMultiple entries represent alternatives (OR)",
    )
    tags: list[str] = Field(..., description="Keywords for categorization and discovery")


class AgentCard(BaseModel):
    capabilities: Capabilities = Field(default_factory=lambda: Capabilities.model_validate({"streaming": False}))
    defaultInputModes: list[str]
    defaultOutputModes: list[str]
    description: str
    name: str
    skills: list[Skill]
    version: str
