# generated by datamodel-codegen:
#   filename:  agenttool_spec_schema.json
#   timestamp: 2026-02-02T21:40:44+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Method(Enum):
    get = "GET"
    post = "POST"
    put = "PUT"
    patch = "PATCH"
    delete = "DELETE"


class ServiceRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description="Name is the service name.", min_length=1)]
    namespace: Annotated[
        str | None,
        Field(description="Namespace is the service namespace. Defaults to the AgentTool's namespace."),
    ] = None
    port: Annotated[
        int | None,
        Field(
            description="Port is the service port number.\nMutually exclusive with PortName.",
            ge=1,
            le=65535,
        ),
    ] = None
    port_name: Annotated[
        str | None,
        Field(
            alias="portName",
            description="PortName is the service port name.\nMutually exclusive with Port.",
        ),
    ] = None


class HttpApi(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    headers: Annotated[
        dict[str, str] | None,
        Field(description="Headers are additional HTTP headers to include in the request."),
    ] = None
    method: Annotated[Method, Field(description="Method is the HTTP method to use for the request.")]
    path: Annotated[
        str | None,
        Field(description="Path is appended to the URL or service endpoint."),
    ] = None
    service_ref: Annotated[
        ServiceRef | None,
        Field(
            alias="serviceRef",
            description="ServiceRef references a Kubernetes service as the target endpoint.\nMutually exclusive with URL.",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(
            alias="timeoutSeconds",
            description="TimeoutSeconds is the request timeout in seconds.",
            ge=1,
            le=300,
        ),
    ] = 30
    url: Annotated[
        str | None,
        Field(description="URL is the external API endpoint to call.\nMutually exclusive with ServiceRef."),
    ] = None


class ConfigMapRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[
        str,
        Field(
            description="Key is the key in the ConfigMap containing the data.",
            min_length=1,
        ),
    ]
    name: Annotated[str, Field(description="Name is the ConfigMap name.", min_length=1)]


class OpenApiSchemaRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config_map_ref: Annotated[
        ConfigMapRef | None,
        Field(
            alias="configMapRef",
            description="ConfigMapRef references a ConfigMap containing the OpenAPI spec.\nMutually exclusive with URL.",
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(description="URL is the endpoint to fetch the OpenAPI spec from.\nMutually exclusive with ConfigMapRef."),
    ] = None


class Type(Enum):
    http_api = "http-api"


class AgentToolSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Annotated[
        str,
        Field(
            description="Description is a human-readable description for the LLM to understand the tool's purpose.",
            min_length=1,
        ),
    ]
    http_api: Annotated[
        HttpApi | None,
        Field(
            alias="httpApi",
            description='HTTPApi contains HTTP API-specific configuration.\nRequired when Type is "http-api".',
        ),
    ] = None
    input_schema: Annotated[
        dict[str, Any] | None,
        Field(
            alias="inputSchema",
            description="InputSchema is a JSON Schema defining the input the agent provides to the tool.\nFor GET requests: becomes query parameters.\nFor POST/PUT/PATCH requests: becomes the JSON body.",
        ),
    ] = None
    open_api_schema_ref: Annotated[
        OpenApiSchemaRef | None,
        Field(
            alias="openApiSchemaRef",
            description="OpenApiSchemaRef references an OpenAPI spec as an alternative to InputSchema/OutputSchema.",
        ),
    ] = None
    output_schema: Annotated[
        dict[str, Any] | None,
        Field(
            alias="outputSchema",
            description="OutputSchema is a JSON Schema defining what the tool returns.",
        ),
    ] = None
    type: Annotated[Type, Field(description="Type specifies the kind of tool (e.g., http-api).")]
