# generated by datamodel-codegen:
#   filename:  managedconfig_schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ManagedConfig(BaseModel):
    """Configuration for a managed agent runtime, mounted from the operator ConfigMap."""

    output_schema: dict[str, Any] | None = Field(
        None,
        alias="outputSchema",
        description="JSON Schema constraining the agent response format",
    )
