# generated by datamodel-codegen:
#   filename:  model_schema.json
#   timestamp: 2026-02-02T21:40:45+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
