# generated by datamodel-codegen:
#   filename:  modelconfig_schema.json
#   timestamp: 2026-02-03T22:12:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ProviderType(Enum):
    openai = "openai"
    anthropic = "anthropic"
    google = "google"
    bedrock = "bedrock"


class OpenAIProviderConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    base_url: Annotated[
        str | None,
        Field(
            alias="baseURL",
            description="BaseURL overrides the default OpenAI API endpoint",
        ),
    ] = None
    organization_id: Annotated[
        str | None,
        Field(
            alias="organizationID",
            description="Organization ID for OpenAI API requests",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(alias="timeoutSeconds", description="Timeout in seconds for API requests"),
    ] = 60


class AnthropicProviderConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    base_url: Annotated[
        str | None,
        Field(
            alias="baseURL",
            description="BaseURL overrides the default Anthropic API endpoint",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(alias="timeoutSeconds", description="Timeout in seconds for API requests"),
    ] = 60


class ServiceAccountKeySecretRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[
        str,
        Field(description="The key of the secret to select from.  Must be a valid secret key."),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
        ),
    ] = ""
    optional: Annotated[
        bool | None,
        Field(description="Specify whether the Secret or its key must be defined"),
    ] = None


class GoogleProviderConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    location: Annotated[
        str | None,
        Field(description='Location is the Google Cloud region (e.g., "us-central1", for Vertex AI)'),
    ] = None
    project: Annotated[
        str | None,
        Field(description="Project is the Google Cloud project ID (for Vertex AI)"),
    ] = None
    service_account_key_secret_ref: Annotated[
        ServiceAccountKeySecretRef | None,
        Field(
            alias="serviceAccountKeySecretRef",
            description="ServiceAccountKeySecretRef references a secret containing the service account JSON key",
        ),
    ] = None
    timeout_seconds: Annotated[
        int | None,
        Field(alias="timeoutSeconds", description="Timeout in seconds for API requests"),
    ] = 60


class BedrockProviderConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    inference_profile_arn: Annotated[
        str | None,
        Field(
            alias="inferenceProfileARN",
            description="InferenceProfileARN is the ARN of the Bedrock inference profile to use",
        ),
    ] = None
    region: Annotated[str | None, Field(description="Region is the AWS region")] = None


class Provider(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[ProviderType, Field(description="The provider type", title="ProviderType")]
    default_headers: Annotated[
        dict[str, str] | None,
        Field(
            alias="defaultHeaders",
            description="Default headers to include in all requests",
        ),
    ] = None
    openai: Annotated[
        OpenAIProviderConfig | None,
        Field(
            description="OpenAI-specific configuration. If set, provider is OpenAI.",
            title="OpenAIProviderConfig",
        ),
    ] = None
    anthropic: Annotated[
        AnthropicProviderConfig | None,
        Field(
            description="Anthropic-specific configuration. If set, provider is Anthropic.",
            title="AnthropicProviderConfig",
        ),
    ] = None
    google: Annotated[
        GoogleProviderConfig | None,
        Field(
            description="Google-specific configuration. If set, provider is Google/Gemini.",
            title="GoogleProviderConfig",
        ),
    ] = None
    bedrock: Annotated[
        BedrockProviderConfig | None,
        Field(
            description="Bedrock-specific configuration. If set, provider is AWS Bedrock.",
            title="BedrockProviderConfig",
        ),
    ] = None


class AnthropicContainer(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    disabled: Annotated[
        bool | None,
        Field(description="Disabled forces a fresh container (ignores any container_id from history)"),
    ] = None
    id: Annotated[
        str | None,
        Field(description='ID is the container ID to use (e.g., "container_xxx")'),
    ] = None


class AnthropicThinkingType(Enum):
    enabled = "enabled"
    disabled = "disabled"


class AnthropicThinking(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    budget_tokens: Annotated[
        int | None,
        Field(
            alias="budgetTokens",
            description="BudgetTokens is the maximum number of tokens for thinking (required when enabled)\nMust be >= 1024 and less than maxTokens",
            ge=1024,
        ),
    ] = None
    type: Annotated[
        AnthropicThinkingType,
        Field(
            description="Type enables or disables extended thinking",
            title="AnthropicThinkingType",
        ),
    ]


class AnthropicModelParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    cache_instructions: Annotated[
        str | None,
        Field(
            alias="cacheInstructions",
            description="CacheInstructions adds cache_control to the last system prompt block\nWhen true, uses TTL='5m'. Can also specify '5m' or '1h' directly.",
        ),
    ] = None
    cache_messages: Annotated[
        str | None,
        Field(
            alias="cacheMessages",
            description="CacheMessages adds a cache point to the last content block in the final user message\nWhen true, uses TTL='5m'. Can also specify '5m' or '1h' directly.",
        ),
    ] = None
    cache_tool_definitions: Annotated[
        str | None,
        Field(
            alias="cacheToolDefinitions",
            description="CacheToolDefinitions adds cache_control to the last tool definition\nWhen true, uses TTL='5m'. Can also specify '5m' or '1h' directly.",
        ),
    ] = None
    container: Annotated[
        AnthropicContainer | None,
        Field(
            description="Container configures container for multi-turn conversations",
            title="AnthropicContainer",
        ),
    ] = None
    metadata_user_id: Annotated[
        str | None,
        Field(
            alias="metadataUserID",
            description="MetadataUserID is an external identifier for the user associated with the request",
        ),
    ] = None
    thinking: Annotated[
        AnthropicThinking | None,
        Field(
            description="Thinking determines whether the model should generate a thinking block\nSee https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking",
            title="AnthropicThinking",
        ),
    ] = None


class BedrockGuardrailTrace(Enum):
    disabled = "disabled"
    enabled = "enabled"
    enabled_full = "enabled_full"


class BedrockGuardrailConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    guardrail_identifier: Annotated[
        str | None,
        Field(
            alias="guardrailIdentifier",
            description="GuardrailIdentifier is the unique identifier of the guardrail",
        ),
    ] = None
    guardrail_version: Annotated[
        str | None,
        Field(
            alias="guardrailVersion",
            description="GuardrailVersion is the version of the guardrail",
        ),
    ] = None
    trace: Annotated[
        BedrockGuardrailTrace | None,
        Field(
            description="Trace controls guardrail tracing level",
            title="BedrockGuardrailTrace",
        ),
    ] = None


class BedrockLatency(Enum):
    optimized = "optimized"
    standard = "standard"


class BedrockPerformanceConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    latency: Annotated[
        BedrockLatency | None,
        Field(
            description="Latency controls performance/cost tradeoff",
            title="BedrockLatency",
        ),
    ] = None


class BedrockServiceTierType(Enum):
    default = "default"
    flex = "flex"
    priority = "priority"
    reserved = "reserved"


class BedrockServiceTier(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[
        BedrockServiceTierType | None,
        Field(
            description="Type specifies the service tier type",
            title="BedrockServiceTierType",
        ),
    ] = None


class BedrockModelParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    additional_model_request_fields: Annotated[
        dict[str, Any] | None,
        Field(
            alias="additionalModelRequestFields",
            description="AdditionalModelRequestFields are additional model-specific parameters to include in requests",
        ),
    ] = None
    additional_model_response_fields_paths: Annotated[
        list[str] | None,
        Field(
            alias="additionalModelResponseFieldsPaths",
            description="AdditionalModelResponseFieldsPaths are JSON paths to extract additional fields from model responses",
        ),
    ] = None
    cache_instructions: Annotated[
        bool | None,
        Field(
            alias="cacheInstructions",
            description="CacheInstructions adds a cache point after the system prompt blocks",
        ),
    ] = None
    cache_messages: Annotated[
        bool | None,
        Field(
            alias="cacheMessages",
            description="CacheMessages adds a cache point to the last content block in the final user message",
        ),
    ] = None
    cache_tool_definitions: Annotated[
        bool | None,
        Field(
            alias="cacheToolDefinitions",
            description="CacheToolDefinitions adds a cache point after the last tool definition",
        ),
    ] = None
    guardrail_config: Annotated[
        BedrockGuardrailConfig | None,
        Field(
            alias="guardrailConfig",
            description="GuardrailConfig defines content moderation and safety settings",
            title="BedrockGuardrailConfig",
        ),
    ] = None
    performance_configuration: Annotated[
        BedrockPerformanceConfig | None,
        Field(
            alias="performanceConfiguration",
            description="PerformanceConfiguration defines performance optimization settings",
            title="BedrockPerformanceConfig",
        ),
    ] = None
    prompt_variables: Annotated[
        dict[str, str] | None,
        Field(
            alias="promptVariables",
            description="PromptVariables are variables for substitution into prompt templates",
        ),
    ] = None
    request_metadata: Annotated[
        dict[str, str] | None,
        Field(
            alias="requestMetadata",
            description="RequestMetadata is additional metadata to attach to Bedrock API requests",
        ),
    ] = None
    service_tier: Annotated[
        BedrockServiceTier | None,
        Field(
            alias="serviceTier",
            description="ServiceTier controls performance and cost optimization",
            title="BedrockServiceTier",
        ),
    ] = None


class GoogleHarmCategory(Enum):
    harm_category_harassment = "HARM_CATEGORY_HARASSMENT"
    harm_category_hate_speech = "HARM_CATEGORY_HATE_SPEECH"
    harm_category_sexually_explicit = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    harm_category_dangerous_content = "HARM_CATEGORY_DANGEROUS_CONTENT"
    harm_category_civic_integrity = "HARM_CATEGORY_CIVIC_INTEGRITY"


class GoogleSafetyMethod(Enum):
    severity = "SEVERITY"
    probability = "PROBABILITY"


class GoogleSafetyThreshold(Enum):
    block_none = "BLOCK_NONE"
    block_low_and_above = "BLOCK_LOW_AND_ABOVE"
    block_medium_and_above = "BLOCK_MEDIUM_AND_ABOVE"
    block_only_high = "BLOCK_ONLY_HIGH"
    off = "OFF"


class GoogleSafetySetting(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    category: Annotated[
        GoogleHarmCategory,
        Field(description="Category is the harm category", title="GoogleHarmCategory"),
    ]
    method: Annotated[
        GoogleSafetyMethod | None,
        Field(
            description="Method specifies if the threshold is used for probability or severity score",
            title="GoogleSafetyMethod",
        ),
    ] = None
    threshold: Annotated[
        GoogleSafetyThreshold,
        Field(
            description="Threshold is the blocking threshold",
            title="GoogleSafetyThreshold",
        ),
    ]


class GoogleThinkingLevel(Enum):
    unspecified = "unspecified"
    minimal = "minimal"
    low = "low"
    medium = "medium"
    high = "high"


class GoogleThinkingConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    include_thoughts: Annotated[
        bool | None,
        Field(
            alias="includeThoughts",
            description="IncludeThoughts indicates whether to include thoughts in the response",
        ),
    ] = None
    thinking_budget: Annotated[
        int | None,
        Field(
            alias="thinkingBudget",
            description="ThinkingBudget is the thinking budget in tokens (0=DISABLED, -1=AUTOMATIC)",
        ),
    ] = None
    thinking_level: Annotated[
        GoogleThinkingLevel | None,
        Field(
            alias="thinkingLevel",
            description="ThinkingLevel controls the amount of thinking tokens the model should generate",
            title="GoogleThinkingLevel",
        ),
    ] = None


class GoogleVideoResolution(Enum):
    unspecified = "unspecified"
    low = "low"
    medium = "medium"
    high = "high"


class GoogleModelParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    cached_content: Annotated[
        str | None,
        Field(
            alias="cachedContent",
            description="CachedContent is the name of the cached content to use for the model",
        ),
    ] = None
    labels: Annotated[
        dict[str, str] | None,
        Field(description="Labels are user-defined metadata to break down billed charges (Vertex AI only)"),
    ] = None
    safety_settings: Annotated[
        list[GoogleSafetySetting] | None,
        Field(
            alias="safetySettings",
            description="SafetySettings configures content safety filters",
        ),
    ] = None
    thinking_config: Annotated[
        GoogleThinkingConfig | None,
        Field(
            alias="thinkingConfig",
            description="ThinkingConfig configures the thinking behavior for the model",
            title="GoogleThinkingConfig",
        ),
    ] = None
    video_resolution: Annotated[
        GoogleVideoResolution | None,
        Field(
            alias="videoResolution",
            description="VideoResolution specifies the video resolution to use for the model",
            title="GoogleVideoResolution",
        ),
    ] = None


class OpenAIReasoningEffort(Enum):
    none = "none"
    minimal = "minimal"
    low = "low"
    medium = "medium"
    high = "high"
    xhigh = "xhigh"


class OpenAIReasoningGenerateSummary(Enum):
    detailed = "detailed"
    concise = "concise"


class OpenAIReasoningSummary(Enum):
    detailed = "detailed"
    concise = "concise"
    auto = "auto"


class OpenAIServiceTier(Enum):
    auto = "auto"
    default = "default"
    flex = "flex"
    priority = "priority"


class OpenAITextVerbosity(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class OpenAITruncation(Enum):
    disabled = "disabled"
    auto = "auto"


class OpenAIModelParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    include_code_execution_outputs: Annotated[
        bool | None,
        Field(
            alias="includeCodeExecutionOutputs",
            description="IncludeCodeExecutionOutputs includes code execution results in the response",
        ),
    ] = None
    include_file_search_results: Annotated[
        bool | None,
        Field(
            alias="includeFileSearchResults",
            description="IncludeFileSearchResults includes file search results in the response",
        ),
    ] = None
    include_raw_annotations: Annotated[
        bool | None,
        Field(
            alias="includeRawAnnotations",
            description="IncludeRawAnnotations includes raw annotations in the response",
        ),
    ] = None
    include_web_search_sources: Annotated[
        bool | None,
        Field(
            alias="includeWebSearchSources",
            description="IncludeWebSearchSources includes web search results in the response",
        ),
    ] = None
    log_probs: Annotated[
        bool | None,
        Field(alias="logProbs", description="LogProbs enables returning log probabilities"),
    ] = None
    previous_response_id: Annotated[
        str | None,
        Field(
            alias="previousResponseID",
            description='PreviousResponseID is the ID of a previous response to continue from\nWhen set to "auto", automatically uses the most recent provider_response_id',
        ),
    ] = None
    prompt_cache_key: Annotated[
        str | None,
        Field(
            alias="promptCacheKey",
            description="PromptCacheKey is the key for prompt caching",
        ),
    ] = None
    prompt_retention: Annotated[
        str | None,
        Field(
            alias="promptRetention",
            description="PromptRetention controls prompt caching retention",
        ),
    ] = None
    reasoning_effort: Annotated[
        OpenAIReasoningEffort | None,
        Field(
            alias="reasoningEffort",
            description="ReasoningEffort controls the reasoning effort for reasoning models (o1, o3, etc.)",
            title="OpenAIReasoningEffort",
        ),
    ] = None
    reasoning_generate_summary: Annotated[
        OpenAIReasoningGenerateSummary | None,
        Field(
            alias="reasoningGenerateSummary",
            description="ReasoningGenerateSummary controls reasoning summary generation",
            title="OpenAIReasoningGenerateSummary",
        ),
    ] = None
    reasoning_summary: Annotated[
        OpenAIReasoningSummary | None,
        Field(
            alias="reasoningSummary",
            description="ReasoningSummary controls reasoning summary format",
            title="OpenAIReasoningSummary",
        ),
    ] = None
    send_reasoning_ids: Annotated[
        bool | None,
        Field(
            alias="sendReasoningIDs",
            description="SendReasoningIDs enables sending reasoning IDs",
        ),
    ] = None
    service_tier: Annotated[
        OpenAIServiceTier | None,
        Field(
            alias="serviceTier",
            description="ServiceTier specifies the service tier for requests",
            title="OpenAIServiceTier",
        ),
    ] = None
    text_verbosity: Annotated[
        OpenAITextVerbosity | None,
        Field(
            alias="textVerbosity",
            description="TextVerbosity controls text verbosity level",
            title="OpenAITextVerbosity",
        ),
    ] = None
    top_log_probs: Annotated[
        int | None,
        Field(
            alias="topLogProbs",
            description="TopLogProbs specifies the number of top log probabilities to return",
        ),
    ] = None
    truncation: Annotated[
        OpenAITruncation | None,
        Field(
            description="Truncation controls response truncation",
            title="OpenAITruncation",
        ),
    ] = None
    user: Annotated[
        str | None,
        Field(description="User is the user identifier associated with the requests"),
    ] = None


class ModelParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    anthropic: Annotated[
        AnthropicModelParameters | None,
        Field(
            description="Anthropic contains Anthropic-specific parameters (only set for Anthropic providers)",
            title="AnthropicModelParameters",
        ),
    ] = None
    bedrock: Annotated[
        BedrockModelParameters | None,
        Field(
            description="Bedrock contains AWS Bedrock-specific parameters (only set for Bedrock providers)",
            title="BedrockModelParameters",
        ),
    ] = None
    extra_body: Annotated[
        dict[str, Any] | None,
        Field(alias="extraBody", description="ExtraBody to include in all requests"),
    ] = None
    extra_headers: Annotated[
        dict[str, str] | None,
        Field(alias="extraHeaders", description="ExtraHeaders to include in all requests"),
    ] = None
    frequency_penalty: Annotated[
        str | None,
        Field(
            alias="frequencyPenalty",
            description='FrequencyPenalty penalizes frequent tokens (-2.0 to 2.0)\nSpecified as a string to avoid floating point issues (e.g., "0.5", "-1.0")',
            pattern="^-?[0-2](\\.\\d+)?$",
        ),
    ] = None
    google: Annotated[
        GoogleModelParameters | None,
        Field(
            description="Google contains Google/Gemini-specific parameters (only set for Google providers)",
            title="GoogleModelParameters",
        ),
    ] = None
    logit_bias: Annotated[
        dict[str, int] | None,
        Field(
            alias="logitBias",
            description="LogitBias modifies the likelihood of specified tokens appearing",
        ),
    ] = None
    max_tokens: Annotated[
        int | None,
        Field(
            alias="maxTokens",
            description="MaxTokens is the maximum number of tokens to generate",
            ge=1,
        ),
    ] = None
    openai: Annotated[
        OpenAIModelParameters | None,
        Field(
            description="OpenAI contains OpenAI-specific parameters (only set for OpenAI providers)",
            title="OpenAIModelParameters",
        ),
    ] = None
    parallel_tool_calls: Annotated[
        bool | None,
        Field(
            alias="parallelToolCalls",
            description="ParallelToolCalls enables parallel tool calling where supported",
        ),
    ] = None
    presence_penalty: Annotated[
        str | None,
        Field(
            alias="presencePenalty",
            description='PresencePenalty penalizes tokens already present in the context (-2.0 to 2.0)\nSpecified as a string to avoid floating point issues (e.g., "0.5", "-1.0")',
            pattern="^-?[0-2](\\.\\d+)?$",
        ),
    ] = None
    seed: Annotated[
        int | None,
        Field(description="Seed for deterministic generation (where supported)"),
    ] = None
    stop_sequences: Annotated[
        list[str] | None,
        Field(
            alias="stopSequences",
            description="StopSequences are sequences where the model will stop generating",
        ),
    ] = None
    temperature: Annotated[
        str | None,
        Field(
            description='Temperature controls randomness in the output (0.0 to 2.0)\nSpecified as a string to avoid floating point issues (e.g., "0.7", "1.0")',
            pattern="^(0(\\.\\d+)?|1(\\.0+)?|2(\\.0+)?)$",
        ),
    ] = None
    time_out: Annotated[
        int | None,
        Field(
            alias="timeOut",
            description="TimeOut in seconds for the model response",
            ge=1,
        ),
    ] = None
    top_k: Annotated[
        int | None,
        Field(
            alias="topK",
            description="TopK limits the number of tokens to consider for each step",
            ge=1,
        ),
    ] = None
    top_p: Annotated[
        str | None,
        Field(
            alias="topP",
            description='TopP controls nucleus sampling (0.0 to 1.0)\nSpecified as a string to avoid floating point issues (e.g., "0.9", "0.95")',
            pattern="^(0(\\.\\d+)?|1(\\.0+)?)$",
        ),
    ] = None


class ModelConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: Annotated[
        Provider,
        Field(
            description="Provider contains provider type and connection configuration",
            title="Provider",
        ),
    ]
    model: Annotated[
        str,
        Field(description="The model identifier (e.g., gpt-4o, claude-sonnet-4-20250514)"),
    ]
    parameters: Annotated[
        ModelParameters | None,
        Field(
            description="Parameters contains base model parameters and optional provider-specific parameters",
            title="ModelParameters",
        ),
    ] = None
