# generated by datamodel-codegen:
#   filename:  templateConfig_schema.json
#   timestamp: 2026-02-13T14:20:47+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class OutputSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    json_schema: Annotated[Any, Field(alias="jsonSchema")]
    name: str


class TemplateConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    output_schema: Annotated[
        OutputSchema,
        Field(
            alias="outputSchema",
            description="OutputSchema defines the JSON Schema for constraining agent response format.",
            title="OutputSchema",
        ),
    ]
    input_schema: Annotated[Any | None, Field(alias="inputSchema", title="InputSchema")] = None
