package spec

import (
	"embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/danielnyari/flokoa/internal/domain/capability"
)

//go:embed baselines/*.json
var baselineFS embed.FS

// RunnerBaseline loads the embedded runner baseline for a runner version: the
// release's Python minor, pydantic-ai pin, and the full lockfile closure.
// Generated by `make runner-contract` in sdk/python (gen_runner_manifest.py)
// and drift-gated by `make verify-runner-contract`; capability admission
// (roadmap 08) evaluates requires tuples and dependency conflicts against it.
func RunnerBaseline(runnerVersion string) (capability.RunnerInfo, error) {
	raw, err := baselineFS.ReadFile(fmt.Sprintf("baselines/runner-baseline-%s.json", runnerVersion))
	if err != nil {
		return capability.RunnerInfo{}, fmt.Errorf(
			"no embedded runner baseline for runner version %q (supported: %s): %w",
			runnerVersion, strings.Join(SupportedRunnerVersions(), ", "), err,
		)
	}

	var doc struct {
		RunnerVersion string            `json:"runnerVersion"`
		Python        string            `json:"python"`
		PydanticAI    string            `json:"pydantic-ai"`
		Packages      map[string]string `json:"packages"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return capability.RunnerInfo{}, fmt.Errorf("parsing embedded baseline for runner %s: %w", runnerVersion, err)
	}

	return capability.RunnerInfo{
		RunnerVersion: doc.RunnerVersion,
		Python:        doc.Python,
		PydanticAI:    doc.PydanticAI,
		Baseline:      doc.Packages,
	}, nil
}
