package spec

import (
	"embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/danielnyari/flokoa/internal/domain/capability"
)

//go:embed baselines/*.json
var baselineFS embed.FS

// SupportedBaselineVersions lists the runner versions with an embedded
// baseline. Normally identical to SupportedRunnerVersions (both artifacts are
// generated by the same `make runner-contract` run), but listed from the
// baseline embed itself so an unknown-version error never reports a version
// whose baseline is actually missing.
func SupportedBaselineVersions() []string {
	entries, err := baselineFS.ReadDir("baselines")
	if err != nil {
		return nil
	}
	versions := make([]string, 0, len(entries))
	for _, e := range entries {
		name := e.Name()
		if v, ok := strings.CutPrefix(name, "runner-baseline-"); ok {
			versions = append(versions, strings.TrimSuffix(v, ".json"))
		}
	}
	sort.Strings(versions)
	return versions
}

// RunnerBaseline loads the embedded runner baseline for a runner version: the
// release's Python minor, pydantic-ai pin, and the full lockfile closure.
// Generated by `make runner-contract` in sdk/python (gen_runner_manifest.py)
// and drift-gated by `make verify-runner-contract`; capability admission
// (roadmap 08) evaluates requires tuples and dependency conflicts against it.
func RunnerBaseline(runnerVersion string) (capability.RunnerInfo, error) {
	raw, err := baselineFS.ReadFile(fmt.Sprintf("baselines/runner-baseline-%s.json", runnerVersion))
	if err != nil {
		return capability.RunnerInfo{}, fmt.Errorf(
			"no embedded runner baseline for runner version %q (supported: %s): %w",
			runnerVersion, strings.Join(SupportedBaselineVersions(), ", "), err,
		)
	}

	var doc struct {
		RunnerVersion string            `json:"runnerVersion"`
		Python        string            `json:"python"`
		PydanticAI    string            `json:"pydantic-ai"`
		Packages      map[string]string `json:"packages"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return capability.RunnerInfo{}, fmt.Errorf("parsing embedded baseline for runner %s: %w", runnerVersion, err)
	}

	return capability.RunnerInfo{
		RunnerVersion: doc.RunnerVersion,
		Python:        doc.Python,
		PydanticAI:    doc.PydanticAI,
		Baseline:      doc.Packages,
	}, nil
}
