package spec

import (
	"embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/danielnyari/flokoa/internal/domain/capability"
)

//go:embed baselines/*.json
var baselineFS embed.FS

// SupportedBaselineVersions lists the runner versions with an embedded
// baseline. Normally identical to SupportedRunnerVersions (both artifacts are
// generated by the same `make runner-contract` run), but listed from the
// baseline embed itself so an unknown-version error never reports a version
// whose baseline is actually missing.
func SupportedBaselineVersions() []string {
	entries, err := baselineFS.ReadDir("baselines")
	if err != nil {
		return nil
	}
	versions := make([]string, 0, len(entries))
	for _, e := range entries {
		name := e.Name()
		if v, ok := strings.CutPrefix(name, "runner-baseline-"); ok {
			versions = append(versions, strings.TrimSuffix(v, ".json"))
		}
	}
	sort.Strings(versions)
	return versions
}

// BuiltinCapabilityInfo is the offline source of truth for one built-in
// capability baked into a runner image (source: builtin; architecture §2.4).
// It is embedded in the operator baseline so admission can validate a builtin
// CR with no artifact to read — the name, entrypoint, and schemaDigest must
// match this metadata, and the compiler runs the same requires/schema/conflict
// checks against it that artifact-backed capabilities get.
type BuiltinCapabilityInfo struct {
	// Entrypoint is the Python module:Class resolving to the capability class
	// in the runner's own environment.
	Entrypoint string
	// SerializationName is the compiled-spec entry name when the class
	// overrides pydantic-ai's default (the class name); empty means the
	// default (the entrypoint attr).
	SerializationName string
	// Requires is the compatibility tuple pinned to the runner's own versions.
	Requires capability.Requires
	// Dependencies is the pinned dependency closure for conflict detection.
	// Built-ins are part of the baseline, so this is always empty.
	Dependencies []string
	// SchemaDigest binds the configSchema to the CR mirror: a builtin CR's
	// schemaDigest must match this so it can't claim a different schema.
	SchemaDigest string
	// ConfigSchema is the JSON Schema for the built-in's per-agent config,
	// kept raw so the webhook can compare its canonical digest and the
	// compiler can validate attachment config against it.
	ConfigSchema json.RawMessage
}

// builtinCapabilityDoc is the on-disk JSON shape of a built-in metadata entry
// (camelCase to match the generator's output and the runner manifest).
type builtinCapabilityDoc struct {
	Entrypoint        string          `json:"entrypoint"`
	SerializationName string          `json:"serializationName"`
	Requires          requiresDoc     `json:"requires"`
	Dependencies      []string        `json:"dependencies"`
	SchemaDigest      string          `json:"schemaDigest"`
	ConfigSchema      json.RawMessage `json:"configSchema"`
}

// requiresDoc matches the manifest/baseline requires keys (the runtime
// contract uses hyphenated package names as JSON keys).
type requiresDoc struct {
	Python       string `json:"python"`
	PydanticAI   string `json:"pydantic-ai"`
	FlokoaRunner string `json:"flokoa-runner"`
}

// baselineDoc is the parsed embedded baseline.
type baselineDoc struct {
	RunnerVersion       string                          `json:"runnerVersion"`
	Python              string                          `json:"python"`
	PydanticAI          string                          `json:"pydantic-ai"`
	Packages            map[string]string               `json:"packages"`
	BuiltinCapabilities map[string]builtinCapabilityDoc `json:"builtinCapabilities"`
}

func parseBaseline(runnerVersion string) (baselineDoc, error) {
	raw, err := baselineFS.ReadFile(fmt.Sprintf("baselines/runner-baseline-%s.json", runnerVersion))
	if err != nil {
		return baselineDoc{}, fmt.Errorf(
			"no embedded runner baseline for runner version %q (supported: %s): %w",
			runnerVersion, strings.Join(SupportedBaselineVersions(), ", "), err,
		)
	}
	var doc baselineDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		return baselineDoc{}, fmt.Errorf("parsing embedded baseline for runner %s: %w", runnerVersion, err)
	}
	return doc, nil
}

// RunnerBaseline loads the embedded runner baseline for a runner version: the
// release's Python minor, pydantic-ai pin, and the full lockfile closure.
// Generated by `make runner-contract` in sdk/python (gen_runner_manifest.py)
// and drift-gated by `make verify-runner-contract`; capability admission
// (roadmap 08) evaluates requires tuples and dependency conflicts against it.
func RunnerBaseline(runnerVersion string) (capability.RunnerInfo, error) {
	doc, err := parseBaseline(runnerVersion)
	if err != nil {
		return capability.RunnerInfo{}, err
	}
	return capability.RunnerInfo{
		RunnerVersion: doc.RunnerVersion,
		Python:        doc.Python,
		PydanticAI:    doc.PydanticAI,
		Baseline:      doc.Packages,
	}, nil
}

// BuiltinCapability returns the embedded built-in metadata for (runnerVersion,
// name): the offline source of truth admission validates a source: builtin CR
// against (architecture §2.4). The bool is false when the runner version has no
// embedded baseline or the name is not a built-in for that runner — either case
// is a "this is not a real built-in for this runner" denial, never a fetch.
func BuiltinCapability(runnerVersion, name string) (BuiltinCapabilityInfo, bool) {
	doc, err := parseBaseline(runnerVersion)
	if err != nil {
		return BuiltinCapabilityInfo{}, false
	}
	entry, ok := doc.BuiltinCapabilities[name]
	if !ok {
		return BuiltinCapabilityInfo{}, false
	}
	return BuiltinCapabilityInfo{
		Entrypoint:        entry.Entrypoint,
		SerializationName: entry.SerializationName,
		Requires: capability.Requires{
			Python:       entry.Requires.Python,
			PydanticAI:   entry.Requires.PydanticAI,
			FlokoaRunner: entry.Requires.FlokoaRunner,
		},
		Dependencies: entry.Dependencies,
		SchemaDigest: entry.SchemaDigest,
		ConfigSchema: entry.ConfigSchema,
	}, true
}
