"""Capability CR YAML generation.

The CR spec mirrors the artifact manifest **by value** (the invariant
``flokoa capability push`` maintains). The spec is validated through the
generated ``flokoa_types.capability.CapabilitySpec`` model — regenerated from
the CRD by ``make generate-python-models`` — so the mirror cannot drift from
the CRD shape.
"""

from __future__ import annotations

import re
from typing import Any

import yaml
from flokoa_types.capability import CapabilitySpec
from pydantic import ValidationError

from flokoa.capability_cli.artifact import ArtifactManifest
from flokoa.capability_cli.errors import CapabilityCliError

#: Digest placeholder written by `build`; `flokoa capability push` rewrites it
#: with the pushed digest. Deliberately NOT a syntactically valid digest:
#: applying an unpushed CR fails admission loudly instead of referencing a
#: digest that does not exist.
DIGEST_PLACEHOLDER = "DIGEST-PENDING"

_VALIDATION_DIGEST = "0" * 64

# RFC 1123 DNS subdomain — what the API server accepts for metadata.name and
# what the capability wheelhouse directory is named after.
_DNS_SUBDOMAIN = re.compile(r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$")

_CR_HEADER = """\
# Generated by `flokoa capability build`.
# spec.artifact carries a placeholder digest — run `flokoa capability push`
# to push the artifact, record the real digest, and rewrite this file.
# Admission refuses the CR until the placeholder is replaced.
"""


def validate_cr_name(name: str) -> str:
    if len(name) > 253 or not _DNS_SUBDOMAIN.match(name):
        raise CapabilityCliError(
            f"capability name {name!r} is not a DNS-safe Kubernetes object name "
            "(lowercase alphanumerics, '-' and '.', max 253 chars) — pass --name"
        )
    return name


def capability_cr_doc(name: str, tag: str, manifest: ArtifactManifest, *, permissive: bool = False) -> dict[str, Any]:
    """Build the Capability CR document, spec-validated through flokoa_types."""
    validate_cr_name(name)

    spec: dict[str, Any] = {
        "artifact": f"{tag}@sha256:{DIGEST_PLACEHOLDER}",
        "version": manifest.version,
        "entrypoint": manifest.entrypoint,
        "requires": {},
    }
    if manifest.requires.python:
        spec["requires"]["python"] = manifest.requires.python
    if manifest.requires.pydantic_ai:
        spec["requires"]["pydanticAI"] = manifest.requires.pydantic_ai
    if manifest.requires.flokoa_runner:
        spec["requires"]["flokoaRunner"] = manifest.requires.flokoa_runner
    if manifest.serialization_name:
        spec["serializationName"] = manifest.serialization_name
    if manifest.dependencies:
        spec["dependencies"] = list(manifest.dependencies)
    if permissive:
        spec["schemaPolicy"] = "permissive"
    elif manifest.config_schema is not None:
        spec["configSchema"] = manifest.config_schema
    else:
        raise CapabilityCliError(
            "a strict Capability CR needs a configSchema — derive one, pass --schema, or opt into --permissive"
        )

    # Validate the mirror through the generated CRD model. The digest
    # placeholder is deliberately pattern-invalid, so substitute a
    # syntactically valid digest for validation only.
    validation_spec = {**spec, "artifact": f"{tag}@sha256:{_VALIDATION_DIGEST}"}
    try:
        CapabilitySpec.model_validate(validation_spec)
    except ValidationError as exc:
        raise CapabilityCliError(f"generated Capability spec does not validate against the CRD model: {exc}") from exc

    return {
        "apiVersion": "agent.flokoa.ai/v1alpha1",
        "kind": "Capability",
        "metadata": {"name": name},
        "spec": spec,
    }


def render_capability_cr(name: str, tag: str, manifest: ArtifactManifest, *, permissive: bool = False) -> str:
    """Render the CR as YAML with the digest-placeholder header comment."""
    doc = capability_cr_doc(name, tag, manifest, permissive=permissive)
    return _CR_HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


def normalize_dist_name(name: str) -> str:
    """PEP 503 normalization — also DNS-safe by construction."""
    return re.sub(r"[-_.]+", "-", name).lower()
