"""``flokoa capability push`` — publish a built artifact and pin its CR.

crane pushes the build's OCI-layout tar to REF, the recorded digest replaces
the CR's ``@sha256:DIGEST-PENDING`` placeholder (the invariant: the CR spec
mirrors the artifact manifest by value, bound to the pushed digest), then
optionally: cosign sign the digest, ``kubectl apply`` the pinned CR, and
append/replace the entry in a local index checkout.

``run_push`` is the function ``flokoa capability import`` composes — the CLI
never subprocesses into itself.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import click
import yaml
from flokoa_types.capability import CapabilitySpec
from pydantic import ValidationError

from flokoa.capability_cli import cosign as cosign_mod
from flokoa.capability_cli import crane as crane_mod
from flokoa.capability_cli import index as index_mod
from flokoa.capability_cli import kubectl as kubectl_mod
from flokoa.capability_cli.cr import DIGEST_PLACEHOLDER
from flokoa.capability_cli.errors import CapabilityCliError

_PLACEHOLDER_SUFFIX = f"@sha256:{DIGEST_PLACEHOLDER}"

_PUSHED_CR_HEADER = """\
# Generated by `flokoa capability build`; digest recorded by
# `flokoa capability push` — spec.artifact is pinned to the pushed artifact.
"""


@dataclass
class DistArtifacts:
    """The `flokoa capability build` outputs ``push`` consumes."""

    tar: Path
    cr_path: Path
    manifest: dict[str, Any] | None


@dataclass
class PushResult:
    """What happened, for the summary (and for ``import`` to report)."""

    pinned_ref: str
    cr_path: Path
    cr_name: str
    signed: bool
    applied: str | None
    index_file: Path | None


def locate_dist(from_dir: Path) -> DistArtifacts:
    """Find exactly one build's outputs in ``--from``."""
    if not from_dir.is_dir():
        raise CapabilityCliError(
            f"build output directory {from_dir} does not exist — run `flokoa capability build` first (or pass --from)"
        )
    tars = sorted(from_dir.glob("*-artifact.oci.tar"))
    if not tars:
        raise CapabilityCliError(
            f"no *-artifact.oci.tar in {from_dir} — run `flokoa capability build` first (or pass --from)"
        )
    if len(tars) > 1:
        listing = ", ".join(tar.name for tar in tars)
        raise CapabilityCliError(
            f"{from_dir} holds more than one artifact tar ({listing}) — pass --from a single build"
        )
    crs = sorted(from_dir.glob("*.capability.yaml"))
    if not crs:
        raise CapabilityCliError(
            f"no *.capability.yaml in {from_dir} — the Capability CR is missing; re-run `flokoa capability build`"
        )
    if len(crs) > 1:
        listing = ", ".join(cr.name for cr in crs)
        raise CapabilityCliError(
            f"{from_dir} holds more than one Capability CR ({listing}) — pass --from a single build"
        )

    manifest: dict[str, Any] | None = None
    manifest_path = from_dir / "manifest.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise CapabilityCliError(f"{manifest_path} is not valid JSON: {exc}") from exc
    return DistArtifacts(tar=tars[0], cr_path=crs[0], manifest=manifest)


def _load_cr(cr_path: Path) -> dict[str, Any]:
    try:
        doc = yaml.safe_load(cr_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise CapabilityCliError(f"could not parse the Capability CR {cr_path}: {exc}") from exc
    if not isinstance(doc, dict) or doc.get("kind") != "Capability":
        raise CapabilityCliError(f"{cr_path} is not a Capability CR")
    return doc


def _check_placeholder(doc: dict[str, Any], cr_path: Path) -> None:
    artifact = doc.get("spec", {}).get("artifact", "")
    if not artifact.endswith(_PLACEHOLDER_SUFFIX):
        raise CapabilityCliError(
            f"the CR {cr_path} does not carry the {_PLACEHOLDER_SUFFIX} placeholder "
            f"(spec.artifact: {artifact!r}) — it looks already pushed; re-run "
            "`flokoa capability build` to produce a fresh CR before pushing again"
        )


def _rewrite_cr(doc: dict[str, Any], cr_path: Path, pinned_ref: str) -> None:
    """Pin spec.artifact, re-validate the mirror, write the CR back."""
    doc["spec"]["artifact"] = pinned_ref
    try:
        CapabilitySpec.model_validate(doc["spec"])
    except ValidationError as exc:
        raise CapabilityCliError(f"pinned Capability spec does not validate against the CRD model: {exc}") from exc
    cr_path.write_text(
        _PUSHED_CR_HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False), encoding="utf-8"
    )


def _index_entry(
    doc: dict[str, Any], manifest: dict[str, Any], *, pinned_ref: str, signed: bool
) -> index_mod.IndexEntry:
    spec = doc["spec"]
    return index_mod.IndexEntry(
        name=doc["metadata"]["name"],
        version=spec["version"],
        artifact=pinned_ref,
        entrypoint=spec.get("entrypoint"),
        requires=manifest.get("requires", {}),
        schema_policy=spec.get("schemaPolicy", "strict"),
        signed=signed,
        keywords=[],
    )


def _update_index(index_path: Path, entry: index_mod.IndexEntry) -> Path:
    index = index_mod.load_or_init_index(index_path)
    index_mod.upsert_entry(index, entry)
    return index_mod.write_index(index, index_path)


def run_push(
    ref: str,
    *,
    from_dir: Path,
    sign: bool = False,
    cosign_key: Path | None = None,
    apply: bool = False,
    namespace: str | None = None,
    index_path: Path | None = None,
) -> PushResult:
    """The push pipeline, reusable as a function (``import`` composes it)."""
    if "@" in ref:
        raise CapabilityCliError("REF must be a tag reference — the digest is recorded from the push itself")

    dist = locate_dist(from_dir)
    doc = _load_cr(dist.cr_path)
    _check_placeholder(doc, dist.cr_path)
    if index_path is not None and dist.manifest is None:
        raise CapabilityCliError(f"--index needs {from_dir / 'manifest.json'} — re-run `flokoa capability build`")

    # Preflight every binary the requested options need before pushing bytes.
    crane = crane_mod.find_crane()
    cosign = cosign_mod.find_cosign() if sign else None
    kubectl = kubectl_mod.require_kubectl() if apply else None

    click.echo(f"Pushing {dist.tar.name} to {ref}...")
    digest = crane_mod.push_oci_archive(dist.tar, ref, crane=crane)
    pinned_ref = f"{ref}@{digest}"
    click.echo(f"Pushed {pinned_ref}")

    if cosign is not None:
        mode = "key-based" if cosign_key is not None else "keyless"
        click.echo(f"Signing {digest} ({mode})...")
        cosign_mod.sign_digest(pinned_ref, cosign=cosign, key=cosign_key)

    _rewrite_cr(doc, dist.cr_path, pinned_ref)
    cr_name = doc["metadata"]["name"]
    click.echo(f"Rewrote {dist.cr_path} (spec.artifact pinned)")

    applied: str | None = None
    if kubectl is not None:
        applied = kubectl_mod.apply_manifest(dist.cr_path, kubectl=kubectl, namespace=namespace)
        click.echo(applied)

    index_file: Path | None = None
    if index_path is not None:
        assert dist.manifest is not None  # checked above  # noqa: S101
        entry = _index_entry(doc, dist.manifest, pinned_ref=pinned_ref, signed=sign)
        index_file = _update_index(index_path, entry)
        click.echo(f"Index updated: {index_file} ({entry.name}=={entry.version}) — commit and push it to publish")

    if applied is None:
        click.echo(f"Next: kubectl apply -f {dist.cr_path}")
    return PushResult(
        pinned_ref=pinned_ref,
        cr_path=dist.cr_path,
        cr_name=cr_name,
        signed=sign,
        applied=applied,
        index_file=index_file,
    )


@click.command()
@click.argument("ref")
@click.option(
    "--from",
    "from_dir",
    type=click.Path(file_okay=False, path_type=Path),
    default=Path("dist"),
    show_default=True,
    help="Build output directory holding the artifact tar, CR, and manifest.",
)
@click.option("--sign/--no-sign", default=False, show_default=True, help="cosign sign the pushed digest.")
@click.option(
    "--cosign-key",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=None,
    help="Key-based signing; omitted with --sign means keyless (ambient OIDC).",
)
@click.option("--apply", "apply_", is_flag=True, help="kubectl apply the digest-pinned CR.")
@click.option("--namespace", default=None, help="Namespace for --apply.")
@click.option(
    "--index",
    "index_path",
    type=click.Path(path_type=Path),
    default=None,
    help="Local checkout of the index file/repo to append or update (you commit it).",
)
def push(
    ref: str,
    from_dir: Path,
    sign: bool,
    cosign_key: Path | None,
    apply_: bool,
    namespace: str | None,
    index_path: Path | None,
) -> None:
    """Push the built artifact to REF and pin the Capability CR to its digest.

    \b
    Reads --from (default ./dist) as produced by `flokoa capability build`:
      <name>-artifact.oci.tar -> crane push REF, digest recorded
      <name>.capability.yaml  -> spec.artifact rewritten to REF@sha256:<digest>
    """
    if cosign_key is not None and not sign:
        raise click.UsageError("--cosign-key needs --sign")
    if namespace is not None and not apply_:
        raise click.UsageError("--namespace needs --apply")
    run_push(
        ref,
        from_dir=from_dir,
        sign=sign,
        cosign_key=cosign_key,
        apply=apply_,
        namespace=namespace,
        index_path=index_path,
    )
