{{- if and .Values.dex.enabled .Values.dex.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flokoa.dex.fullname" . }}-credentials
  namespace: {{ include "flokoa.namespace" . }}
  labels:
    {{- include "flokoa.dex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.dex.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
