{{- if and .Values.server.enabled .Values.server.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flokoa.server.fullname" . }}-reader
  labels:
    {{- include "flokoa.server.labels" . | nindent 4 }}
rules:
  # Read-only access to Flokoa CRDs
  - apiGroups:
      - agent.flokoa.ai
    resources:
      - agents
      - agenttools
      - instructions
      - modelproviders
      - models
    verbs:
      - get
      - list
      - watch
  # Read-only access to CRD statuses
  - apiGroups:
      - agent.flokoa.ai
    resources:
      - agents/status
      - agenttools/status
      - instructions/status
      - modelproviders/status
      - models/status
    verbs:
      - get
{{- end }}
