{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flokoa.server.fullname" . }}
  namespace: {{ include "flokoa.namespace" . }}
  labels:
    {{- include "flokoa.server.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.server.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flokoa.server.selectorLabels" . | nindent 4 }}
{{- end }}
