---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.flokoa.ai
  resources:
  - agents
  - agenttools
  - modelconfigs
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.flokoa.ai
  resources:
  - agents/finalizers
  - agenttools/finalizers
  - modelconfigs/finalizers
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - agent.flokoa.ai
  resources:
  - agents/status
  - agenttools/status
  - modelconfigs/status
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
