apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flokoa
    app.kubernetes.io/managed-by: kustomize
  name: flokoa-workflow-agent-reader
rules:
- apiGroups:
  - agent.flokoa.ai
  resources:
  - agents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
