apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: flokoa
    app.kubernetes.io/managed-by: kustomize
  name: flokoa-workflow-agent-reader-binding
subjects:
- kind: ServiceAccount
  name: flokoa-workflow
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flokoa-workflow-agent-reader
