apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: flokoa
    app.kubernetes.io/managed-by: kustomize
  name: flokoa-workflow.service-account-token
  namespace: system
  annotations:
    kubernetes.io/service-account.name: flokoa-workflow
type: kubernetes.io/service-account-token
