apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: flokoa
    app.kubernetes.io/managed-by: kustomize
  name: flokoa-workflow-executor-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: flokoa-workflow
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flokoa-workflow-executor
