resources:
- deployment.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/danielnyari/flokoa-operator
  newTag: 0.0.20
