apiVersion: agent.flokoa.ai/v1alpha1
kind: AgentWorkflow
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: agentworkflow-sample
spec:
  # TODO(user): Add fields here
