## Append samples of your project ##
resources:
- agent_v1alpha1_agent.yaml
- agent_v1alpha1_agent_managed.yaml
- agent_v1alpha1_agenttool.yaml
- agent_v1alpha1_instruction.yaml
- agent_v1alpha1_modelprovider.yaml
- agent_v1alpha1_model.yaml
- agent_v1alpha1_instruction.yaml
- agent_v1alpha1_agentworkflow.yaml
- agent_v1alpha1_agenttrigger.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
