## Append samples of your project ##
resources:
- agent_v1alpha1_agent.yaml
- agent_v1alpha1_agenttool.yaml
- agent_v1alpha1_model.yaml
- agent_v1alpha1_modelconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
