# Adds namespace to all resources.
namespace: flokoa-e2e-2a04ac4a

resources:
- ../crd
- ../rbac
- ../manager
- ../server
- metrics_service.yaml

patches:
- path: manager_metrics_patch.yaml
  target:
    kind: Deployment
    name: flokoa-controller
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
